### ISSUE TITLE
Use multiple threads / processes while indexing

### ISSUE THREAD

**Issue by Str1ker17** [bootlin/elixir#101]
Is it possible to make elixir index a project in multiple threads simultaneously?
I have a very large codebase and 6 cores / 12 threads CPU, but elixir is running only one thread out of 12 possible, and I have to wait for a long time.

**Comment by michaelopdenacker** [comment]
Hi,
This must be very frustrating indeed. 
Though you can index multiple projects in parallel, this is not yet possible to index a single project with mutiple threads. 
This is part of our todo list and will be adressed when we switch to another database design, using self balancing search trees. I hope we can find a solution that allows muitiple processes to query and feed the database in parallel, if that's possible.
Anyway, the goal is to make database access much faster, which may be a sufficient relief for big projects such as the Linux kernel sources...
Thanks for asking!
Cheers,
Michael.
