### ISSUE TITLE
Branches with slashes

### ISSUE THREAD

**Issue by Mephistophiles** [bootlin/elixir#106]
Branches with slashes not supported

For example:
repo glibc, branch fedora/glibc-2.12.90-6

https://elixir.bootlin.com/glibc/latest/source -- latest
https://elixir.bootlin.com/glibc/fedora/glibc-2.12.90-6/source -- `` fedora/glibc-2.12.90-6`` branch.

Slash in a branch breaks web routing.

**Comment by michaelopdenacker** [comment]
Hi,
Good catch. Thank you for reporting this issue!
Indeed, Elixir uses the slash character to distinguish the project name from the version, etc.

See the below code in http/web.py:

> # Split the URL into its components (project, version, cmd, arg)
> m = search('^/([^/]*)/([^/]*)/([^/]*)(.*)$', url)
> 
> if m:
>     project = m.group(1)
>     version = m.group(2)
>     cmd = m.group(3)
>     arg = m.group(4)

At the moment, I don't really know how to address this, except by ignoring the "fedora/" tags which probably make much less sense than the upstream ones.

Would you agree?

I'll also address the bad menu hierarchies (as revealed by the "FIXME" strings).

Cheers,
Michael.

**Comment by cxw42** [comment]
Could we URL-encode the slash?

**Comment by michaelopdenacker** [comment]
Hey, good idea!
Then we would decode it to get the real tag name back.
This would make Elixir more robust indeed...
Michael.

**Comment by Mephistophiles** [comment]
> Could we URL-encode the slash?
Good idea!

**Comment by michaelopdenacker** [comment]
Re-opening. The menu links now seem correct, but we still get a 404 error:
Example: https://elixir.bootlin.com/glibc/fedora%2Fglibc-2.11.90-20/source

**Comment by michaelopdenacker** [comment]
Oops, I was missing the "AllowEncodedSlashes On" statement in Apache's configuration.
Fixed now.
