### ISSUE TITLE
function attributes seems to confuse the parser

### ISSUE THREAD

**Issue by lunn** [bootlin/elixir#11]
I was searching for kernfs_drain() but this symbol is not known.

http://elixir.free-electrons.com/linux/latest/source/fs/kernfs/dir.c#L456

I think the issue is the attributes after the declaration, __releases(&kernfs_mutex) __acquires(&kernfs_mutex). There are other functions with such attribute missing, e.g.  debugfs_use_file_finish() it knows of the EXPORT, but not the function. fuse_send_writepage() is referenced, but not defined.

**Comment by chleroy** [comment]
Same issue with finish_task_switch() in kernel/sched/core.c, for the same reason.
