### ISSUE TITLE
Support for context-dependent searching of identifiers

### ISSUE THREAD

**Issue by elfring** [bootlin/elixir#111]
It can occur that [the definition (or meaning) of identifiers depends on the scope](https://en.wikipedia.org/wiki/Namespace "Description for the usage of name spaces") in which they are used.
Does the query interface handle the lookup of names also together with selected source code positions?

**Comment by tpetazzoni** [comment]
This is too vague, so there's no way to understand what you're expecting. Please be more specific with an actual example, and also ensure that what you request is actually feasible.

**Comment by elfring** [comment]
>This is too vague, so there's no way to understand what you're expecting.

:crystal_ball: Can undesirable communication difficulties be adjusted anyhow also for this issue?

Will development interests grow for safer handling of source code scopes? :thinking:

**Comment by tpetazzoni** [comment]
Sorry, but I also don't understand your new two comments. Could you clarify?

**Comment by elfring** [comment]
:thought_balloon: I imagine that you can be familiar with scopes.
:eyes: How will they influence source code searches?
