### ISSUE TITLE
Missing file instantiating a symbol 

### ISSUE THREAD

**Issue by michaelopdenacker** [bootlin/elixir#116]
rtc_set_time() appears in https://elixir.bootlin.com/linux/v5.7-rc2/source/drivers/rtc/systohc.c#L55, but when you follow the hyperlink, this file ("systohc.c") doesn't appear in the list of files instantiating this symbol.

Thanks to Lukas Wunner for reporting this issue!

**Comment by l1k** [comment]
ISTR it worked fine yesterday. I'm using elixir all the time, hence am suffering serious substance withdrawal syndrome right now. %-)

**Comment by michaelopdenacker** [comment]
Weird because we didn't update the Elixir version recently (but soon will be).
We'll find out why this happened.
Michael.

**Comment by michaelopdenacker** [comment]
The issue is now gone after the database update. I'm not sure why though.
Don't hesitate to open a new bug if this kind of behavior happens again.
Thanks again,
Michael.
