### ISSUE TITLE
fatal: not a git repository

### ISSUE THREAD

**Issue by marmalodak** [bootlin/elixir#119]
I'm trying to follow the installation instructions. I'm stuck at this point. Please let me know what I can do to get past this.

	[root@elixir-js elixir]# pwd
	/usr/local/elixir
	[root@elixir-js elixir]# ls 
	api      data.py  find-file-doc-comments.pl  lib.py    __pycache__  README.adoc  script.sh  templates  utils
	COPYING  docker   http                       projects  query.py     samples      t          update.py
	[root@elixir-js elixir]# cat .git/config 
	[core]
		repositoryformatversion = 0
		filemode = true
		bare = false
		logallrefupdates = true
	[remote "origin"]
		url = https://github.com/bootlin/elixir.git
		fetch = +refs/heads/*:refs/remotes/origin/*
	[branch "master"]
		remote = origin
		merge = refs/heads/master
	[root@elixir-js elixir]# ./script.sh list-tags
	fatal: not a git repository (or any of the parent directories): .git

**Comment by cxw42** [comment]
What steps have you done so far?  Have you set the LXR* environment variables?

As a basic test, run `prove` and see if all the tests pass.  If not, you may be missing a dependency.

**Comment by marmalodak** [comment]
After figuring out what `prove` is, I ran it:

        [root@elixir-js elixir]# prove
        t/100-basic.t ......... 1/? # Using temporary directory /tmp/d6gEch5llH
        # Running git init /tmp/d6gEch5llH
        # git exited with value 0
        # Running bash -c tar cf - -C "/usr/local/elixir/t/tree" . | tar xf - -C "/tmp/d6gEch5llH"
        # bash exited with value 0
        # Running git -C /tmp/d6gEch5llH add .
        # git exited with value 0
        # Running git -C /tmp/d6gEch5llH commit -am Initial commit
        # git exited with value 0
        # Running git -C /tmp/d6gEch5llH tag v5.4
        # git exited with value 0
        # Running /usr/local/elixir/update.py
        # /usr/local/elixir/update.py exited with value 0
        t/100-basic.t ......... 6/? # Running /usr/local/elixir/query.py v5.4 ident SOME_NONEXISTENT_IDENTIFIER_XYZZY_PLUGH
        t/100-basic.t ......... 14/? # Running /usr/local/elixir/query.py v5.4 ident i2c_acpi_notify
        # Running /usr/local/elixir/query.py v5.4 file /SOME_NONEXISTENT_FILENAME_XYZZY_PLUGH
        # Running /usr/local/elixir/query.py v5.4 file /drivers/i2c/i2c-dev.c
        # Running /usr/local/elixir/query.py v5.4 file /drivers/i2c/i2c-dev.c
        # Running /usr/local/elixir/query.py v5.4 file /drivers/i2c/i2c-core.h
        t/100-basic.t ......... ok    
        t/200-api.t ........... # Using temporary directory /tmp/lhvPLrcZ75
        # Running git init /tmp/lhvPLrcZ75
        # git exited with value 0
        # Running bash -c tar cf - -C "/usr/local/elixir/t/tree" . | tar xf - -C "/tmp/lhvPLrcZ75"
        # bash exited with value 0
        # Running git -C /tmp/lhvPLrcZ75 add .
        # git exited with value 0
        # Running git -C /tmp/lhvPLrcZ75 commit -am Initial commit
        # git exited with value 0
        # Running git -C /tmp/lhvPLrcZ75 tag v5.4
        # git exited with value 0
        # Running /usr/local/elixir/update.py
        # /usr/local/elixir/update.py exited with value 0
        # Running pytest -v
        open3: exec of pytest -v failed: No such file or directory at /usr/local/elixir/t/TestHelpers.pm line 210.
        t/200-api.t ........... Dubious, test returned 2 (wstat 512, 0x200)
        No subtests run 
        t/300-doc-comments.t .. # Using temporary directory /tmp/GZPssiwRrK
        # Running git init /tmp/GZPssiwRrK
        # git exited with value 0
        # Running bash -c tar cf - -C "/usr/local/elixir/t/tree" . | tar xf - -C "/tmp/GZPssiwRrK"
        # bash exited with value 0
        # Running git -C /tmp/GZPssiwRrK add .
        # git exited with value 0
        # Running git -C /tmp/GZPssiwRrK commit -am Initial commit
        # git exited with value 0
        # Running git -C /tmp/GZPssiwRrK tag v5.4
        # git exited with value 0
        # Running /usr/local/elixir/update.py
        # /usr/local/elixir/update.py exited with value 0
        t/300-doc-comments.t .. 1/? # Running /usr/local/elixir/query.py v5.4 ident SOME_NONEXISTENT_IDENTIFIER_XYZZY_PLUGH
        # Running /usr/local/elixir/query.py v5.4 ident gsb_buffer
        # Running /usr/local/elixir/query.py v5.4 ident i2c_acpi_get_i2c_resource
        # Running /usr/local/elixir/query.py v5.4 ident documented_function_XYZZY
        t/300-doc-comments.t .. ok    

        Test Summary Report
        -------------------
        t/200-api.t         (Wstat: 512 Tests: 0 Failed: 0)
          Non-zero exit status: 2
          Parse errors: No plan found in TAP output
        Files=3, Tests=53, 11 wallclock secs ( 0.03 usr  0.01 sys +  7.00 cusr  4.98 csys = 12.02 CPU)
        Result: FAIL
        [root@elixir-js elixir]# echo $LXR_DATA_DIR 
        /elixir/rs-cfe/data
        [root@elixir-js elixir]# echo $LXR_REPO_DIR 
        /elixir/rs-cfe/repo
        [root@elixir-js elixir]# pwd
        /usr/local/elixir

**Comment by cxw42** [comment]
OK!  The success of 100 and 300 tells me you aren't missing anything script.sh requires, at least for list-tags.  The failure in 200 is missing pytest-3, which is only a test dependency.

Is /elixir/rs-cfe/repo a git repo?  Tracing through script.sh, it looks like that's the first place a git operation happens.

If it still doesn't work, would you please start over and paste your full terminal contents here?  Without having seen your full setup, it's hard to tell what the issue might be.  Plus, that would be a great help to future readers.  Thanks!

**Comment by michaelopdenacker** [comment]
I agree with Chris. You may have ran commands in two different terminal windows, without the same environment settings.

Here's what I would try:
cd /usr/local/elixir
export LXR_DATA_DIR=/elixir/rs-cfe/data
export LXR_REPO_DIR=/elixir/rs-cfe/repo
ls -la $LXR_REPO_DIR/.git (please share the output with us)
./update.py

I hope this helps,
Cheers,
Michael.

**Comment by marmalodak** [comment]
I haven't had a chance to work on this, and when I finally did, it turns out it was a [PEBKAC](https://en.wiktionary.org/wiki/PEBCAK). My apologies.
