### ISSUE TITLE
Jump directly to symbol definition if it's on the same file you're on

### ISSUE THREAD

**Issue by carmeli-tamir** [bootlin/elixir#121]
The use case is when reviewing a code in some file, one might want to jump to function or struct definitions that appear on the same file.
Currently when clicking an identifier, you go to the identifier page, and then choose the definition which is at the same file you were in before.

My suggestion is to add a hover \ pop up (I don't claim to be a UI expert) to allow easy navigation in the same file, saving the extra click to the identifier page. Maybe even do the same for identifiers which aren't on the same file, but have just one definition.

WDYT?

**Comment by cxw42** [comment]
Good idea!  Other options include a mode selector in the header, a custom right-click menu, and a shift+click or similar.

**Comment by Mephistophiles** [comment]
+1. Needed for me

**Comment by tpetazzoni** [comment]
We believe this issue has been resolved by the introduction of a pop-up when you click on a symbol, rather than going to a different page.
