### ISSUE TITLE
api.py ignores the project name in the URL when testing

### ISSUE THREAD

**Issue by cxw42** [bootlin/elixir#129]
Per @carmeli-tamir at https://github.com/bootlin/elixir/pull/108#issuecomment-631685120 , the project is passed to the API as part of the path.  However, when testing, api.py uses the database in `LXR_DATA_DIR` regardless of the project portion of the path.  Repro (master @ f6ce332b1433fe38099852a4d2a08343b29c3e8f), with this repo checked out in $SRC:

    $ cd $SRC
    $ pip3 install uwsgi
    $ perl t/interact.pl

In the resulting subshell:

    $ cd $SRC
    $ uwsgi --http :9090 --wsgi-file api/api.py

Then, in another terminal:

    $ curl http://localhost:9090/ident/NONEXISTENT_PROJECT/of_i2c_get_board_info?version=latest

I expect a 404, since `NONEXISTENT_PROJECT` doesn't exist.  However, I get JSON:

    {"definitions": [{"path": "drivers/i2c/i2c-core-of.c", "line": 22, "type": "function"}, {"path": "drivers/i2c/i2c-core-of.c", "line": 62, "type": "variable"}, {"path": "include/linux/i2c.h", "line": 968, "type": "function"}, {"path": "include/linux/i2c.h", "line": 941, "type": "prototype"}], "references": [{"path": "drivers/i2c/i2c-core-of.c", "line": "22,62,73", "type": null}, {"path": "include/linux/i2c.h", "line": "941,968", "type": null}]}

I believe this is because, in api.py, if both LXR_DATA_DIR and LXR_REPO_DIR exist, LXR_PROJ_DIR and the project are ignored:

https://github.com/bootlin/elixir/blob/f6ce332b1433fe38099852a4d2a08343b29c3e8f/api/api.py#L10-L14

It looks to me like line 11 should be removed.  

Also, I don't know enough about Falcon to know why line 12 is pulling from `env` rather than from `os.environ`.

What say you?

**Edit** [falcon.Request](https://falcon.readthedocs.io/en/stable/api/request_and_response.html#falcon.Request) says that `req.env` is a PEP-3333 environment.  [PEP-3333](https://www.python.org/dev/peps/pep-3333/#environ-variables) says:

> the environ dictionary **may** also contain arbitrary operating-system "environment variables"

(emphasis original).  That makes me think that `req.env` is not a reliable way to access `LXR_PROJ_DIR`.  However, I could certainly be wrong!

**Comment by cxw42** [comment]
I think the changes I just pushed (https://github.com/cxw42/elixir/commit/dc92ec4c6d3283aeb687ad215431561e8f440fcf) may be a solution.  If you agree, let me know, and I'll open a PR.  If you disagree, I look forward to learning why! :)

**Comment by MaximeChretien** [comment]
Hi,
It looks fine for me but I see one problem, LXR_PROJ_DIR is defined by apache and api.py doesn't seems to have access to that, on my computer at least.

I don't know if it's possible to allow api.py to access apache env, maybe something to do with mod_wgsi ?
Or maybe just add a line on the README explaining that LXR_PROJ_DIR needs to be defined to have a working api ?

**Comment by cxw42** [comment]
Thanks for testing!  Does req.env include LXR_PROJ_DIR in your configuration?  If so, we can use req.env as a fallback if the key is missing from os.environ, right?

**Comment by MaximeChretien** [comment]
It works fine with req.env instead of os.environ.
And in the original code LXR_PROJ_DIR come from req.env so I think it's where apache define it.
I think we should not use req.env as a fallback but use it as the main way to get LXR_PROJ_DIR, so it always has the same value as the one the web server has.

**Comment by cxw42** [comment]
Sounds reasonable!  Since uwsgi doesn't provide req.env['LXR_PROJ_DIR'], I'll submit a PR with os.environ as the fallback to req.env.

**Comment by michaelopdenacker** [comment]
Accepted, thanks!
