### ISSUE TITLE
Autocomplete/fuzzy in identifier search?

### ISSUE THREAD

**Issue by michaelopdenacker** [bootlin/elixir#13]
A suggestion from Bram Vlerick <vlerickb@gmail.com>...

Are there any plans to make the search identifier do some kind of autocomplete/fuzzy search?

**Comment by michaelopdenacker** [comment]
Would there be a way to carry a list of known identifiers for a given version, which wouldn't have to be carried in each page? Can this be done through a per version .js file that would be loaded in the browser cache?

**Comment by zo** [comment]
On the frontend, the way to do this is to use AJAX with on-the-fly requests to the backend returning a JSON or CSV string.
If the routing url and mimetypes are well made the browser should automatically cache the results.

**Comment by MaximeChretien** [comment]
Solved by https://github.com/bootlin/elixir/pull/159
