### ISSUE TITLE
definition of struct class

### ISSUE THREAD

**Issue by pdp7** [bootlin/elixir#131]
I am looking for definition of `struct class` such as this line:
https://elixir.bootlin.com/linux/v5.7-rc6/source/drivers/pwm/sysfs.c#L476
```
static struct class pwm_class = {
```
The results are:
https://elixir.bootlin.com/linux/v5.7-rc6/ident/class
```
Defined in 2 files:
drivers/infiniband/hw/hfi1/device.c, line 56 (as a variable)
tools/usb/usbip/libsrc/names.c, line 37 (as a struct)
```
which is missing the most important definition:
```
pdp7@x1:~/dev/beaglebone/omap2plus-mainline-linux/KERNEL$ git grep 'struct class {' include/
include/linux/device/class.h:struct class {
```

**Comment by masatake** [comment]
I guess bootlin runs C++ parser of ctags for parsing .h file.
"class" is a keyword of C++, so the parser doesn't recognize it as an identifier.

Adding  `--langmap=c:+.h` to ctags command line makes ctags use C parser for .h files.
https://github.com/bootlin/elixir/blob/4781abde0501533ed1dcba4053fbe64668919770/script.sh#L164

**Comment by MaximeChretien** [comment]
Hi,
It looks like this has been fixed in the new version of ctags we will use soon, it's reported properly as a struct on my computer and my test server.

Maxime

**Comment by pdp7** [comment]
@MaximeChretien @masatake 
Thanks for the followup.  "class" is a tricky one.

Greg KH joked in a talk that there is no way Linux will ever be able to compiled as C++ :)

**Comment by cxw42** [comment]
Confirming that ctags detects `struct class` on my Lubuntu Eoan installation using the packaged universal-ctags, ver. 0+git20181215-2.

**Comment by masatake** [comment]
If you know the target source code is written in C, I recommend you to use --langmap=c:+.h option.
This is applicable even if you use the latest u-ctags.

**Comment by cxw42** [comment]
Would that be project-specific?  As far as I know, Elixir could be used on C++ projects.

I am submitting a PR adding a test for `struct class` just in case u-ctags changes in the future.

**Comment by masatake** [comment]
If you know the language used in the target source code (in a project) is C,  passing --langmap=c:+.h may make better results. However, C, C++ (and/or Objective-C) are mixed in a target source tree, --langmap=c:+.h doesn't help. If you can accept performance penalty, -G option can improve the result.
With -G option, u-ctags inspects the content of target input for guessing proper language before parsing.

**Comment by MaximeChretien** [comment]
Yes this has to be project specific because C++ can be used in other projects. What can be done is to redefine parse_defs_C in projects/linux.sh 
I'll do some tests to see if it's relevant or not, maybe it will fix https://github.com/bootlin/elixir/issues/61
But if it doesn't change anything I don't think it's useful to add that because it will add useless complexity in the code and it will be harder to make new changes 

And I don't think we can really accept some performance penalty here because it takes already multiple days to create the full database...
