### ISSUE TITLE
Report kernel-doc for enum, struct, and #define

### ISSUE THREAD

**Issue by cxw42** [bootlin/elixir#134]
Forked off #78 per https://github.com/bootlin/elixir/issues/78#issuecomment-632611233 .

**Edit** while updating the parser, fix the missing docs at:
- https://elixir.bootlin.com/linux/v4.9.140/source/drivers/base/regmap/regmap.c#L2714
- https://elixir.bootlin.com/linux/v4.9.140/source/kernel/sched/completion.c#L111
- https://elixir.bootlin.com/linux/latest/ident/v4l2_fwnode_endpoint_parse (documented [here](https://elixir.bootlin.com/linux/latest/source/include/media/v4l2-fwnode.h#L216)) (as of v5.8.9)

**Comment by michaelopdenacker** [comment]
Closed by mistake

**Comment by cxw42** [comment]
I plan to work on this in October.  @michaelopdenacker would you please assign it to me?  Thanks!

**Comment by michaelopdenacker** [comment]
Hi Chris,

On 9/28/20 12:59 AM, Chris White wrote:
>
> I plan to work on this in October. @michaelopdenacker
> <https://github.com/michaelopdenacker> would you please assign it to
> me? Thanks!
>

That was actually a trivial one. I accepted it.

Thank you for your help anyway.

Cheers,

Michael.

-- 

Michael Opdenacker, CEO, Bootlin
Embedded Linux and Kernel engineering
https://bootlin.com

**Comment by cxw42** [comment]
@michaelopdenacker I'm sorry to say I don't understand your note above.  Has this been fixed on a branch?  The fix isn't in `master` yet --- line 50 is one of the lines that needs to change:

https://github.com/bootlin/elixir/blob/00e55918b3dc387f9aa5e57431fda659215e2276/find-file-doc-comments.pl#L47-L52

**Comment by michaelopdenacker** [comment]
Oops, I was replying to another pull request, apparently. My apologies!

**Comment by cxw42** [comment]
No worries!

**Comment by cxw42** [comment]
WIP at https://github.com/cxw42/elixir/tree/issue-134

**Comment by michaelopdenacker** [comment]
Hi Chris,
The database with this change is now live on https://elixir.bootlin.com.
Thanks again!
Michael
