### ISSUE TITLE
Implement symbol autocompletion in search form

### ISSUE THREAD

**Issue by michaelopdenacker** [bootlin/elixir#146]
Hello,

Someone once suggested to implement autocompletion for existing symbols in the current version of the current project.

There could be some javascript code that gets the list of symbols the current version of the current project, and would then help you make your search by showing existing symbols that match what you started typing.

I hope you can find existing open-source code (with a license compatible to Elixir's) that implements such a functionality given a list of allowable symbols.

As far as I know, there is no query yet to retrieve the list of symbols for a given version, so you may need to add one. Performance to retrieve such symbols will matter too. I hope the javascript code including the list of symbols will be cachable by the cache we use in front of Apache...

Thanks in advance for considering this improvement...

**Comment by cxw42** [comment]
An interim step might be wild cards -  e.g., a search for `nvmem*` could return all the symbols starting with nvmem.  That would provide much of the functionality without requiring js.
