### ISSUE TITLE
Missing symbol documentation in U-Boot

### ISSUE THREAD

**Issue by michaelopdenacker** [bootlin/elixir#147]
Hello,

Here's a symbol that does have documentation, but there is no documentation in search results:
https://elixir.bootlin.com/u-boot/latest/C/ident/FIELD_FIT

I checked that there is a symbol documentation database for U-Boot though...

Michael.

**Comment by cxw42** [comment]
I suggest closing this as a duplicate of #134.

**Comment by michaelopdenacker** [comment]
Agreed, thanks
