### ISSUE TITLE
Missing functions in ASM

### ISSUE THREAD

**Issue by MaximeChretien** [bootlin/elixir#150]
Functions defined by the ENTRY() macro (in linux) are not indexed in the definition database.
The problem is that ctags doesn't know about those macro which is normal.

I don't know if there is an easy way to add thoses functions in the database and to fix that problem :/

Example : 
https://elixir.bootlin.com/linux/latest/source/arch/arm/lib/memset.S#L17 should be listen in definitions here : 
https://elixir.bootlin.com/linux/latest/A/ident/memset but it's only in references

**Comment by cxw42** [comment]
#151 modifies script.sh to run a separate grep over *.S files after running ctags, and produce ctags-style output.  Let me know what you think!

**Comment by MaximeChretien** [comment]
Thanks a lot for that ! I'll make some test :D 
At first I just opened this to remind me to do it later :smile:
