### ISSUE TITLE
Incomplete descriptions in SEO results

### ISSUE THREAD

**Issue by michaelopdenacker** [bootlin/elixir#167]
Looking for "Linux Cross Reference", the Qwant search engine finds https://elixir.bootlin.com, but without any description, except:
"We would like to show you a description here but the site won’t allow us."

Same issue on Bing. According to their documentation, we should fix our robots.txt file:
https://www.bing.com/webmaster/info/missinginfo

With Google, we just have the title page and the "description" header: Elixir Cross Referencer"
For this case, we should expand the "description" header to be more explicit.

I'll take care of this. Don't hesitate to make suggestions.

**Comment by michaelopdenacker** [comment]
Addressed the second part (description header) through https://github.com/bootlin/elixir/commit/53c160b34930355738d00c9c5edb94305be5d2d1

**Comment by michaelopdenacker** [comment]
Here's our robots.txt on our server, it doesn't seem to ban search engines:
User-Agent: *
Allow: /
Crawl-Delay: 5

Investigating...

**Comment by michaelopdenacker** [comment]
@VinceHillier any idea ?

**Comment by fstachura** [comment]
According to official Google Docs, the issue with missing description could be related to the fact that the description is the same for all pages. I think what we could try is generating a description that depends on the contents of the page. 

https://developers.google.com/search/docs/appearance/snippet#create-unique-descriptions-for-each-page-on-your-site

Bing does not care and just shows the default description.

**Comment by tleb** [comment]
Google is indexing us correctly and not hiding our description. Here are Google, Qwant and Kagi first results for the "clk elixir" query, all with a OK-ish description:

<details>

![image](https://github.com/user-attachments/assets/36c95315-c2eb-42f3-b3f7-4b9e600d8a3a)

![image](https://github.com/user-attachments/assets/861d5349-ff60-4b70-bf50-2266402fe644)

![image](https://github.com/user-attachments/assets/1e11ea62-7731-42cf-b529-749296202921)

</details>

Does Google change its behavior with different people? Do other search engines have the issue? It seems like the issue can be closed?

**Comment by fstachura** [comment]
@tleb Interesting, the main page does not have a description 
![image](https://github.com/user-attachments/assets/d8cd9e75-d275-4530-ad78-7a7196aa311f)

**Comment by fstachura** [comment]
Same with a search Linux Cross Reference
![image](https://github.com/user-attachments/assets/8ab51a01-bb26-440c-a1d8-6dce684f004d)

**Comment by fstachura** [comment]
This was fixed with #314
