### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by ghost** [bootlin/elixir#17]
Debian Web Server 

**Need to migrate to debian testing to get python3.5, Doesn't work with python3.4.** 

As root : 
root@debian:~ git clone git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git
root@debian:~ git clone https://github.com/free-electrons/elixir.git
root@debian:~ aptitude install python3 python3-pygments python3-jinja2 exuberant-ctags kamailio-berkeley-modules python3-bsddb3 

root@debian:~ mkdir /root/data
root@debian:~ export LXR_REPO_DIR=/root/linux
root@debian:~ export LXR_DATA_DIR=/root/data

root@debian:~ cd elixir
root@debian:~ ./update.py #changed update.py to create only the last tag
root@debian:~ mv /root/linux/ /srv/elixir-data/linux/repo
root@debian:~ mv /root/data /srv/elixir-data/linux/
root@debian:~ mv /root/elixir/ /usr/local/

Add to apache2.conf : 
<pre><code>&lt;Directory /usr/local/elixir/http/&gt;
    Options +ExecCGI
    AllowOverride None
    Require all granted
    SetEnv PYTHONIOENCODING utf-8
    SetEnv LXR_PROJ_DIR /srv/elixir-data
&lt;/Directory&gt;

AddHandler cgi-script .py

&lt;VirtualHost *:80&gt;
    ServerName MY_LOCAL_IP
    DocumentRoot /usr/local/elixir/http

    RewriteEngine on
    RewriteRule "^/$" "/linux/latest/source" [R]
    RewriteRule "^/.*/(source|ident|search)" "/web.py" [PT]
&lt;/VirtualHost&gt;
</code></pre>

root@debian:~ a2enmod rewrite
root@debian:~ a2enmod cgi
root@debian:~ systemctl restart apache2

**Comment by modelrockettier** [comment]
The kamailio-berkeley-modules package is unnecessary

**Comment by 0x0916** [comment]
Shall we add the these instructions to `README` file? or we can write an `Dockerfile` to get an environment for generate the databases.

**Comment by darx0r** [comment]
see #28 :)

**Comment by michaelopdenacker** [comment]
I believe this has now been addresses. 
Don't hesitate to open a new bug if you still see missing details in the instructions.
Thanks!
