### ISSUE TITLE
Issue running utils/update-elixir-data

### ISSUE THREAD

**Issue by michaelopdenacker** [bootlin/elixir#174]
Hello,

I'm running into trouble trying to update the database on the server, running Ubuntu 18.04:

```
lxrng:~> /usr/local/elixir/utils/update-elixir-data /srv/elixir-data-20200629d
Processing project /srv/elixir-data-20200629d/linux ...
Fetching origin
remote: Enumerating objects: 1652, done.
remote: Counting objects: 100% (1652/1652), done.
remote: Compressing objects: 100% (785/785), done.
remote: Total 1762 (delta 1186), reused 1047 (delta 866), pack-reused 110
Receiving objects: 100% (1762/1762), 1.62 MiB | 6.44 MiB/s, done.
Resolving deltas: 100% (1237/1237), completed with 297 local objects.
From git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux
 * branch                      HEAD       -> FETCH_HEAD
 * [new tag]                   v5.8-rc4   -> v5.8-rc4
Fetching other
From git://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable
   9ebcfadb0610..dcb7fd82c75e  master     -> other/master
Fetching other2
linux - found 1 new tags
linux - v5.8-rc4: 207 new blobs (100%)
Exception in thread UpdateDefsElixir:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "./update.py", line 140, in run
    self.update_definitions(new_idxes[self.index][0])
  File "./update.py", line 164, in update_definitions
    line = int(line.decode())
ValueError: invalid literal for int() with base 10: 'menu'
```

Then, the process hangs. If I run "strace" on the "python3 ./update.py" process, I find the it is waiting forever for a lock that is never released:
futex(0x7f5fe8000e70, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, 0xffffffff

I have to kill this process to move on to the next repository and database to update, and I get the same issues (error + locking issue).

Any idea why?
Cheers,
Michael.

**Comment by michaelopdenacker** [comment]
Could not reproduce yet on Ubuntu 20.04...
According the @MaximeChretien , the locking issue happens because of the process that crashed (and didn't release the lock).

**Comment by MaximeChretien** [comment]
Yes it's probably the thread indexing references that waits on a lock (an Event in this case), and this lock is released by the thread indexing definitions... but this thread is the one who crashed so the lock is never released ...

**Comment by MaximeChretien** [comment]
The error comes from a problem in the ctags output, maybe because ctags is returning an error instead of a correct output ...

If you can only reproduce this error on the server running ubuntu 18.04, maybe try to reinstall the last version of ctags you can find in the README and then try to reproduce the error again

**Comment by tpetazzoni** [comment]
Issue is old, back then only happened on Ubuntu 18.04, and the script has seen quite a few changes since then. Let's assume it's fixed, until someone encounters the issue again (if ever).
