### ISSUE TITLE
Elixir is slow to respond to most requests

### ISSUE THREAD

**Issue by tbodt** [bootlin/elixir#178]
```
$ time curl https://elixir.bootlin.com/linux/latest/source >/dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  348k  100  348k    0     0   264k      0  0:00:01  0:00:01 --:--:--  264k
        1.32 real         0.01 user         0.01 sys
$ time curl https://elixir.bootlin.com/linux/latest/source/Makefile > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  669k    0  669k    0     0   102k      0 --:--:--  0:00:06 --:--:--  163k
        6.57 real         0.01 user         0.03 sys
$ time curl https://elixir.bootlin.com/linux/latest/source/Makefile > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  669k  100  669k    0     0   444k      0  0:00:01  0:00:01 --:--:--  444k
        1.51 real         0.01 user         0.01 sys
$ time curl https://elixir.bootlin.com/acp\?q=console_initca\&f=A\&p=linux
[
"console_initcall"]
        0.62 real         0.01 user         0.00 sys
```
For listing directories or files I can do the same operation on a local git tree in much less time.

**Comment by MaximeChretien** [comment]
Hi,

I think the reasons behind that is that Elixir don't just use some git commands but also format the output and often have to read its database, which is a 15GB database for the linux kernel, so obviously the time needed to load a page is higher than just the time needed for the git command

Getting files is probably the slowest element because Elixir apply different filters to each files to create all the links and also use Pygments to generate a syntax highlighted version of the file which takes a lot of time

Maybe there are ways to improve the speed of Elixir but I don't really know how. Maybe you have ideas about that ?

**Comment by tbodt** [comment]
I suspect the combination of python, shell, and CGI is a big source of the slowness. Syntax highlighting and database lookups are not this slow.

**Comment by MaximeChretien** [comment]
Yes it probably doesn't help to have fast server response but solving that would require to rewrite the whole server I think :/
Maybe there are ways to speedup the system without rewriting everything ^^'

**Comment by jmberg** [comment]
From a Python POV, one thing that's probably slow (but should measure it) is that it uses this strange

{noformat}
exec(open('something.py').read())
{noformat}

construction all the time. This means that python cannot pre-compile the content of those files. Doing this in a more python way, e.g. importing the file using importlib and then calling a function inside of it, might be faster.

**Comment by tleb** [comment]
It is true Elixir can be rather slow. We need to measure to know what is the slow part. The `exec(open().read())` stuff is ugly but we don't know until we measure if it can be a cause of slowness.

Let's keep that open until we get measurement data to find action points to improve performance.

**Comment by tleb** [comment]
As mentioned in #305, recent work on WSGI + performance improvements have made Elixir much more stable to host and much quicker to respond. It is still rather slow (imagine the amount of computation we can do in ~200ms) but it has not been an issue recently, so we won't be spending too much time on that.

Feel free to discuss here if you disagree, or see leads for optimization.
