### ISSUE TITLE
add mercurial support

### ISSUE THREAD

**Issue by heyleke** [bootlin/elixir#18]
Before I might give it a try, looking at script.sh (which adds the 'git' support to elixir, right?), I believe it would be fairly easy to add hg support? Any suggestions?

**Comment by michaelopdenacker** [comment]
Hi,
Thank you for the suggestion.
Yes, hg support should be manageable to implement, as long as you find equivalents for each git command in script.sh (which may be renamed "git.sh").
Does Mercurial have a similar notions of tree and blob objects?
Anyway, feel free to give it a try and propose some code.
What project source code did you have in mind?
Thanks for proposing your help!
Cheers,
Michael.

**Comment by tpetazzoni** [comment]
We are not going to implement Mercurial support. Mercurial usage has dropped significantly, Elixir is tightly coupled with Git, so I'm afraid Mercurial is unlikely to ever happen, and will not be implemented by us in any case.
