### ISSUE TITLE
RCS files in early versions of Linux

### ISSUE THREAD

**Issue by michaelopdenacker** [bootlin/elixir#180]
For example:
https://elixir.bootlin.com/linux/0.10/source/RCS/Makefile,v

This files belong to the RCS version control tool. They are not actual source files.
Could they be removed from the repository indexed by https://elixir.bootlin.com ?

**Comment by MaximeChretien** [comment]
It looks like RCS files are only present in version 0.10 so I pushed a fixed branch in linux-history and updated the tag
https://github.com/bootlin/linux-history/tree/0.10-fix-RCS

But I'm wondering if Elixir will update it or not as the name of the tag didn't change :/

**Comment by MaximeChretien** [comment]
It looks like this is fixed now.
