### ISSUE TITLE
Would you be willing to add the `hacktoberfest` topic to this repo?

### ISSUE THREAD

**Issue by cxw42** [bootlin/elixir#185]
I learned after submitting #184 that [Hacktoberfest is opt-in for maintainers this year](https://hacktoberfest.digitalocean.com/hacktoberfest-update).  @michaelopdenacker would you be willing to consider adding the `hacktoberfest` topic to this repo so it could qualify?  Please let me know either way.  Thanks for considering this request!

Apparently the opt-in requirement is a spam-prevention measure.  I opened a number of my repos for Hacktoberfest contributions last year and didn't have any spam problems.  Of course, your experience may be different from mine!

**Comment by michaelopdenacker** [comment]
Thanks for this very nice suggestion. I was unaware of Hacktoberfest.
I will let people know about this opportunity.
Accepted, thanks again
Michael.
