### ISSUE TITLE
find-file-doc-comment: Use of uninitialized value $source_lines[0] in pattern match (m//) at line 118.

### ISSUE THREAD

**Issue by cxw42** [bootlin/elixir#186]
Reported at https://github.com/bootlin/elixir/pull/184#issuecomment-705424428 .

Repro: 
- check out Linux commit 3fdd47c3b40ac48e6e6e5904cf24d12e6e073a96 = v5.9-rc8-201-g3fdd47c3b40a
- run `V=1 find-file-doc-comments.pl arch/arm/common/scoop.c` (copy attached as [scoop.c.gz](https://github.com/bootlin/elixir/files/5352201/scoop.c.gz))

```
...
Checking scoop_resume @ 161
  Regex is -(?^:^(?^:\h+\*\h+(?:(?:struct|enum|union|typedef)\h+)?)scoop_resume(?:\h|\(|:|$))-
  Starting search for docs at line -1
Checking line 0 for header
Use of uninitialized value $source_lines[0] in pattern match (m//) at /home/cxw/proj/elixir/find-file-doc-comments.pl line 118.
```

I'm working on it!

**Comment by michaelopdenacker** [comment]
Pfooh, it seems quite a lot of work to isolate the issue. Thanks a lot!
