### ISSUE TITLE
find-file-doc-comment: Use of uninitialized value $source_lines[0] in pattern match (m//) at line 123.

### ISSUE THREAD

**Issue by michaelopdenacker** [bootlin/elixir#188]
Hello,

An issue remains with find-file-doc-comments.pl, at least with old versions of Linux. These are less frequent than those in https://github.com/bootlin/elixir/issues/186, though.

linux - vers: 2.4.2.4 done (27.3%)
linux - comps: 27000 (9.3%)
Use of uninitialized value $source_lines[0] in pattern match (m//) at /home/mike/github/elixir/find-file-doc-comments.pl line 123.
linux - ids: 2.4.25: 1694 new blobs (29.7%)
linux - vers: 2.4.2.5 done (27.4%)
linux - vers: 2.4.2.6 done (27.4%)
linux - ids: 2.4.26: 661 new blobs (29.7%)
linux - vers: 2.4.2.7 done (27.4%)
linux - ids: 2.4.27: 708 new blobs (29.7%)
linux - vers: 2.4.2.8 done (27.4%)
linux - ids: 2.4.28: 671 new blobs (29.8%)
linux - vers: 2.4.3 done (27.4%)
linux - vers: 2.4.3.1 done (27.5%)
linux - ids: 2.4.29: 735 new blobs (29.8%)

@cxw42, that's for you!
Many thanks for all your contributions!
Michael.

**Comment by michaelopdenacker** [comment]
The issue also happens on versions from the standard Linux git repository:

linux - vers: v2.6.23.12 done (39.3%)
linux - ids: v2.6.30.9: 46 new blobs (43.1%)
linux - vers: v2.6.23.13 done (39.3%)
linux - ids: v2.6.30.10: 3 new blobs (43.1%)
Use of uninitialized value $source_lines[0] in pattern match (m//) at /home/mike/github/elixir/find-file-doc-comments.pl line 123.
linux - vers: v2.6.23.14 done (39.3%)

**Comment by cxw42** [comment]
Thanks for the report and details --- I'll take a look!  (And maybe add some warning trapping so it includes the input filename when there's a warning :D )

**Comment by cxw42** [comment]
I found a repro: `v2.6.23.14:arch/ppc/kernel/ppc_htab.c`.

In case it helps anyone else, here's how I found it

    git diff --name-only v2.6.11 v2.6.23.14 -z | xargs -0 -n1 bash -c 'set -eEuo pipefail ; [[ "$0" == *.[ch] ]] && { fn="foo-$(basename "$0")" ; echo "$0 -> $fn" 1>&2 ; git show v2.6.23.14:"$0" > "$fn" ; ~/proj/elixir/find-file-doc-comments.pl "$fn" >/dev/null ; rm "$fn" ; }' 2>&1 |tee ../names.log
