### ISSUE TITLE
Kernel-doc for request_firmware() in 4.9.140 missing

### ISSUE THREAD

**Issue by cxw42** [bootlin/elixir#192]
https://elixir.bootlin.com/linux/v4.9.140/source/drivers/base/firmware_class.c#L1202

The header line is

     * request_firmware: - send firmware request and wait for it

which I don't think find-file-doc-comments recognizes (`: -` sequence is nonstandard).  I'll take this one unless someone beats me to it :) .

**Comment by bulwahn** [comment]
Always check the source of the latest version (latest linux-next, latest mainline, or latest release candidate or latest release, i.e. v5.9). For v5.9, you find the source now here:

https://elixir.bootlin.com/linux/v5.9/source/drivers/base/firmware_loader/main.c#L806

Andres Rodriguez has fixed this issue in commit c35f9cbb1df8f ("firmware: use () to terminate kernel-doc function names") in May 2018. So, I guess there is nothing left to do here.

**Comment by cxw42** [comment]
@bulwahn I'm glad to know the underlying issue has been fixed!  Thanks for the commit reference.

I want Elixir to be as useful as possible for all versions, not just the latest.  My own use case is v4.9.140 for NVIDIA Jetson devices, so that is where I will most often find issues :) .

**Comment by michaelopdenacker** [comment]
This is a relevant question...
I agree with @cxw42 that we should do our best to support all versions, even if this means supporting deprecated coding styles, at least to the extent that this doesn't create hard to maintain code or wrong results...
Thanks

**Comment by cxw42** [comment]
I was wrong: the problem wasn't the header line.  It was the fact that the type was on the line before the function name.  Fix coming momentarily! :)

**Comment by michaelopdenacker** [comment]
Accepted. Many thanks!
I'll generate a new database when I can.
