### ISSUE TITLE
Symbol definitions appear in references too

### ISSUE THREAD

**Issue by michaelopdenacker** [bootlin/elixir#196]
Symbol definitions also appear in symbol references too.
Example: https://elixir.bootlin.com/linux/latest/C/ident/rtl8150_probe

This is redundant information. Would it be possible to remove the definitions from the references?

**Comment by MaximeChretien** [comment]
I think we can add a test in update.py to avoid indexing definitions in the references.
I'll try that and make some tests to see if it's slows down update.py or not.

**Comment by fstachura** [comment]
It seems that this was fixed by #204
