### ISSUE TITLE
API tests not working in debian docker

### ISSUE THREAD

**Issue by MaximeChretien** [bootlin/elixir#199]
For some reasons the debian docker container can't pass api tests.

`prove` gives this output : https://framabin.org/p/?3a184243d2fb1049#weDViHGUYe/H3foLLfHZ/Sv4M3oqCN72E++aVFbaOy4=

The thing is that the api is working properly when sending requests to the server with curl so it's just the test part that is broken.

I tested with both root and normal user and none of them work.

I also tested if the tests were working fine on other systems (list below) and everything works fine :
- Centos docker
- Arch Linux
- Lubuntu 20.04 (fresh install on virtualbox)

I don't know how we can debug falcon testing system to find and fix this issue.

Maybe @cxw42 have an idea about that ?

**Comment by cxw42** [comment]
I wonder if it's an outdated falcon version.  I see this warning from one of the falcon files:

> Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated,

Perhaps we aren't running the latest, and there's a bug in our version.

**Comment by MaximeChretien** [comment]
As you said it seems to be an outdated version of python3-falcon in Debian buster.

If I remove the `python3-falcon` package and install falcon with `pip3 install falcon` the tests are working fine.
I still get `Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated,` but it doesn't break the tests.

I'll update the dockerfile to use the pip3 version of falcon instead of the debian package.

**Comment by alexandrebelloni** [comment]
Solved by  #202
