### ISSUE TITLE
Problem api ident curl query

### ISSUE THREAD

**Issue by gopunop** [bootlin/elixir#203]
I have indexed zephyr codebase. Both tests `./script.sh list-tags` and `./query.py v2.4.0 ident mimxrt1060_evk_usdhc_pinmux C` are working as expected.

This is my `/etc/apache2/sites-enabled/000-default.conf` file

```

HttpProtocolOptions Unsafe
# Required for HTTP
<Directory /home/user/Downloads/elixir/http/>
    Options +ExecCGI
    AllowOverride None
    Require all granted
    SetEnv PYTHONIOENCODING utf-8
    SetEnv LXR_PROJ_DIR /home/user/Downloads/elixir-data
</Directory>

# Required for the REST API
<Directory /home/user/Downloads/elixir/api/>
    SetHandler wsgi-script
    Require all granted
    SetEnv PYTHONIOENCODING utf-8
    SetEnv LXR_PROJ_DIR /home/user/Downloads/elixir-data
</Directory>

AddHandler cgi-script .py
#Listen 80
<VirtualHost *:80>
    ServerName 127.0.0.1
    DocumentRoot /home/user/Downloads/elixir/http

    # To enable REST api after installing mod_wsgi: Fill path and uncomment:
    #WSGIScriptAlias /api /usr/local/elixir/api/api.py

    AllowEncodedSlashes On

    RewriteEngine on
    RewriteRule "^/$" "/zephyr/latest/source" [R]
    RewriteRule "^/(?!api|acp).*/(source|ident|search)" "/web.py" [PT]
    RewriteRule "^/acp" "/autocomplete.py" [PT]
</VirtualHost>

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet
```

Now, in browser request to http://127.0.0.1/zephyr/latest/source works fine.

But doing `curl http://127.0.0.1/api/ident/zephyr/mimxrt1060_evk_usdhc_pinmux?version=latest` over terminal returns this

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
<hr>
<address>Apache/2.4.29 (Ubuntu) Server at 127.0.0.1 Port 80</address>
</body></html>
```

What is wrong?

**Comment by gopunop** [comment]
So this would only work if the below is done:

> To enable the REST API, follow the installation instructions on mod_wsgi and connect it to the apache installation as detailed in https://github.com/GrahamDumpleton/mod_wsgi#connecting-into-apache-installation.

**Comment by MaximeChretien** [comment]
In theory yes but apparently this part is not always needed, on debian and centos it seems to be configured properly during the package installation.

Maybe this is needed at least `a2enmod cgi rewrite`

**Comment by gopunop** [comment]
Yeah I just tried and it is working. Thanks.
