### ISSUE TITLE
Please consider making a new release

### ISSUE THREAD

**Issue by ghost** [bootlin/elixir#209]
It's been quite a while since last release (v1.0), please consider making a new stable release soon. The v2.1 version that bootlin runs doesn't seem to be present here.

**Comment by cxw42** [comment]
I think that's a reasonable request.  As far as I know, bootlin is running off `master`, so you can grab that if you want the latest.

**Comment by tleb** [comment]
This a **public service announcement**! We are curious to know about other Elixir instances in the wild. If you do host one, please speak up (here or by [email](https://bootlin.com/company/staff/theo-lebrun/)).

Publishing releases sounds like a strictly better option than not making them; but we are uncertain it would actually be useful to anyone. We won't be pouring effort into making tidy releases if they go unused.

---

As mentioned previously, we keep the official instance up to date with the latest changes. A PR is merged once it gets deployed basically. We now use two branches to reflect state: [staging](https://github.com/bootlin/elixir/tree/staging) and [prod](https://github.com/bootlin/elixir/tree/prod). The staging server is currently not public, but might become. The prod branch is code running on the Bootlin server.
