### ISSUE TITLE
Special Pygments build no longer needed?

### ISSUE THREAD

**Issue by aron-silverton** [bootlin/elixir#212]
Hi,

It looks like your changes to Pygments for devicetree and kconfig were merged around v2.7. I see that PyPi has v2.8. Can the PyPi build now be used with Elixir?

Thank you,

Aron

**Comment by aron-silverton** [comment]
Ah, I think that the kconfig changes are not in the upstream yet. I must have been looking at the fork that does have the changes. Apologies.

**Comment by aron-silverton** [comment]
Hi Michael,

I might have been wrong again... I do see the changes to support kconfig* from Maxime's repository in the upstream. Perhaps the PyPi version is safe to use now?

Aron

**Comment by michaelopdenacker** [comment]
I'll check when I have time (next week-end?).
Let's re-open this bug.
Thanks again!
