### ISSUE TITLE
Request: show "defined as syscall" for the functions that implement syscalls

### ISSUE THREAD

**Issue by CS-cwhite** [bootlin/elixir#222]
E.g., `init_module` shows at <https://elixir.bootlin.com/linux/v5.15.1/A/ident/init_module> as "referenced in" `kernel/module.c:4144`.  It would be great if that were instead (or in addition) a "defined as syscall in", since that's where the `SYSCALL_DEFINE3(init_module, ...)` for `init_module(2)` is.  Thanks for considering this request!

(Implementation idea: a separate pass after ctags that greps for `/^SYSCALL_DEFINE\((\w+)/`.  However, since the syscalls are arch-specific, I understand that might not be perfect.)

**Comment by cxw42** [comment]
Thanks very much!
