### ISSUE TITLE
Searching for get_task_mm in the Linux kernel sources leads to a 500 internal server error

### ISSUE THREAD

**Issue by karim-manaouil** [bootlin/elixir#226]
Surprisingly, as stated in the title, searching for `get_task_mm` on [elixir.bootlin.com](https://elixir.bootlin.com/linux/latest/source/kernel) leads to an HTTP error 500. The error seems to happen on all kernel versions and happens on both Firefox and Google Chrome.

**How to reproduce?**

Just search for `get_task_mm` on: 
[https://elixir.bootlin.com/linux/latest/A/ident/get_task_mm](https://elixir.bootlin.com/linux/latest/A/ident/get_task_mm)

**Comment by cxw42** [comment]
Confirmed!

**Comment by michaelopdenacker** [comment]
Thanks for reporting this issue. It actually happens on a bunch of symbols. See the latest occurrences:
/usr/local/elixir/query.py in get_idents_defs(version='v5.18-rc4', ident='spi_transfer', family='A')
/usr/local/elixir/query.py in get_idents_defs(version='v5.15', ident='spi_transfer', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v2.6.33.18', ident='spi_transfer', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v5.18.1', ident='spi_transfer', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='2.2.3', ident='bb', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v5.14.11', ident='read_swap_header', family='A')
/usr/local/elixir/query.py in get_idents_defs(version='v5.4.187', ident='get_task_mm', family='A')
/usr/local/elixir/query.py in get_idents_defs(version='v4.6', ident='get_task_mm', family='A')
/usr/local/elixir/query.py in get_idents_defs(version='v5.10', ident='get_task_mm', family='A')
/usr/local/elixir/query.py in get_idents_defs(version='v5.10.25', ident='spi_message', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v5.18.1', ident='spi_transfer', family='A')
/usr/local/elixir/query.py in get_idents_defs(version='v5.18.1', ident='spi_message', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v5.15.5', ident='spi_message', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v5.18.1', ident='spi_transfer', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v5.18.1', ident='spi_transfer', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v5.18.1', ident='spi_message', family='A')
/usr/local/elixir/query.py in get_idents_defs(version='v5.18.1', ident='spi_message', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v4.4', ident='get_task_mm', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v3.6', ident='spi_transfer', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v3.6', ident='spi_transfer', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v4.4', ident='spi_message', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v5.18.1', ident='spi_message', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v4.9', ident='spi_message', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v5.15.32', ident='EXPORT_SYMBOL', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v4.18', ident='proc_create_data', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v5.18.1', ident='spi_message', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v4.6', ident='spi_transfer', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v5.17', ident='get_task_mm', family='A')
/usr/local/elixir/query.py in get_idents_defs(version='v4.6', ident='get_task_mm', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v5.18.1', ident='spi_transfer', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v5.18.1', ident='spi_transfer', family='A')
/usr/local/elixir/query.py in get_idents_defs(version='v5.18.1', ident='get_task_mm', family='A')
/usr/local/elixir/query.py in get_idents_defs(version='v5.15.32', ident='spi_transfer', family='A')
/usr/local/elixir/query.py in get_idents_defs(version='v5.18.1', ident='spi_message', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v5.18.2', ident='drm_internal_framebuffer_create', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v5.18.2', ident='get_task_mm', family='A')
/usr/local/elixir/query.py in get_idents_defs(version='v5.18.1', ident='spi_transfer', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v4.4.18', ident='proc_create_data', family='A')
/usr/local/elixir/query.py in get_idents_defs(version='v5.18.1', ident='get_task_mm', family='A')
/usr/local/elixir/query.py in get_idents_defs(version='v2.6.27.45', ident='get_task_mm', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v5.10-rc5', ident='drm_internal_framebuffer_create', family='A')
/usr/local/elixir/query.py in get_idents_defs(version='v4.6', ident='get_task_mm', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v4.20.17', ident='get_task_mm', family='A')
/usr/local/elixir/query.py in get_idents_defs(version='v5.17.12', ident='spi_transfer', family='A')
/usr/local/elixir/query.py in get_idents_defs(version='v4.20.17', ident='get_task_mm', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v5.18.1', ident='spi_transfer', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v5.18.1', ident='spi_message', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v5.18-rc7', ident='read_seqretry', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v5.10', ident='get_task_mm', family='A')
/usr/local/elixir/query.py in get_idents_defs(version='v2.6.33.1', ident='get_task_mm', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v4.9.28', ident='spi_transfer', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v5.18.2', ident='battery_scale', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v5.4.196', ident='get_task_mm', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v5.14.11', ident='read_swap_header', family='A')
/usr/local/elixir/query.py in get_idents_defs(version='v5.19-rc1', ident='proc_dir_entry', family='A')
/usr/local/elixir/query.py in get_idents_defs(version='v4.4.18', ident='proc_dir_entry', family='A')
/usr/local/elixir/query.py in get_idents_defs(version='v3.16.53', ident='get_task_mm', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v5.15.44', ident='get_task_mm', family='A')
/usr/local/elixir/query.py in get_idents_defs(version='v4.6', ident='spi_transfer', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v4.9.312', ident='spi_transfer', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v3.16.53', ident='get_task_mm', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v5.18.1', ident='spi_transfer', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v5.18.1', ident='get_task_mm', family='A')
/usr/local/elixir/query.py in get_idents_defs(version='v5.18.1', ident='spi_message', family='A')
/usr/local/elixir/query.py in get_idents_defs(version='v5.2.12', ident='get_task_mm', family='A')
/usr/local/elixir/query.py in get_idents_defs(version='v5.8.18', ident='spi_transfer', family='A')
/usr/local/elixir/query.py in get_idents_defs(version='v5.18.1', ident='spi_transfer', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v4.9', ident='spi_message', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v3.4.48', ident='spi_transfer', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v4.4.22', ident='drm_i915_reg_read', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v4.6', ident='spi_transfer', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v5.15', ident='spi_message', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v5.18.1', ident='spi_transfer', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v4.4', ident='proc_create', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v4.8.12', ident='get_task_mm', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v5.18.1', ident='proc_create_data', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v5.18.1', ident='get_task_mm', family='A')
/usr/local/elixir/query.py in get_idents_defs(version='v4.4', ident='spi_message', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v5.18.1', ident='spi_transfer', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v5.18.1', ident='spi_transfer', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v4.14.277', ident='get_task_mm', family='A')
/usr/local/elixir/query.py in get_idents_defs(version='v5.17.12', ident='spi_message', family='A')
/usr/local/elixir/query.py in get_idents_defs(version='2.0.33pre2', ident='get_task_mm', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v2.6.11', ident='get_task_mm', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v5.2.21', ident='get_task_mm', family='A')
/usr/local/elixir/query.py in get_idents_defs(version='v5.18.1', ident='get_task_mm', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v5.18.1', ident='spi_transfer', family='A')
/usr/local/elixir/query.py in get_idents_defs(version='v5.18.2', ident='v4l2_buffer', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v5.16.20', ident='get_task_mm', family='A')
/usr/local/elixir/query.py in get_idents_defs(version='v4.6', ident='spi_transfer', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v5.18.1', ident='spi_message', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='2.1.5', ident='go_flags', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v5.18.1', ident='spi_message', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v3.6', ident='spi_transfer', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v5.18.1', ident='spi_transfer', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v5.18.1', ident='spi_message', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v4.9', ident='spi_message', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v5.18.1', ident='spi_transfer', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v5.18.1', ident='spi_message', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v5.18', ident='spi_transfer', family='A')
/usr/local/elixir/query.py in get_idents_defs(version='v5.18.1', ident='spi_transfer', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v4.4', ident='spi_message', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v4.3', ident='get_task_mm', family='A')
/usr/local/elixir/query.py in get_idents_defs(version='v5.18', ident='spi_message', family='A')
/usr/local/elixir/query.py in get_idents_defs(version='v2.6.32.71', ident='get_task_mm', family='A')
/usr/local/elixir/query.py in get_idents_defs(version='v4.20.17', ident='proc_create_data', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v5.18.1', ident='get_task_mm', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v5.18.1', ident='spi_transfer', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v5.9', ident='get_task_mm', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v5.18.1', ident='spi_transfer', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v5.16.20', ident='get_task_mm', family='A')
/usr/local/elixir/query.py in get_idents_defs(version='v5.18.2', ident='get_task_mm', family='A')
/usr/local/elixir/query.py in get_idents_defs(version='v5.18.2', ident='proc_create_data', family='A')
/usr/local/elixir/query.py in get_idents_defs(version='v5.18.1', ident='get_task_mm', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v5.14.11', ident='get_task_mm', family='A')
/usr/local/elixir/query.py in get_idents_defs(version='v4.14', ident='proc_create', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v3.10', ident='get_task_mm', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v5.15.44', ident='get_task_mm', family='A')
/usr/local/elixir/query.py in get_idents_defs(version='v5.18.1', ident='spi_transfer', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v5.18.1', ident='spi_transfer', family='A')
/usr/local/elixir/query.py in get_idents_defs(version='v4.9.312', ident='spi_transfer', family='A')
/usr/local/elixir/query.py in get_idents_defs(version='v5.18.1', ident='get_task_mm', family='A')
/usr/local/elixir/query.py in get_idents_defs(version='v3.6', ident='spi_transfer', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v5.2.11', ident='get_task_mm', family='A')
/usr/local/elixir/query.py in get_idents_defs(version='v5.18.1', ident='get_task_mm', family='A')
/usr/local/elixir/query.py in get_idents_defs(version='v4.9', ident='spi_message', family='C')
/usr/local/elixir/query.py in get_idents_defs(version='v4.9.74', ident='spi_message', family='C')

I will investigate, but it may take time...
Cheers
Michael.

**Comment by purplesyringa** [comment]
Not sure if that's the same issue, but I'm getting the same bug for `vfs_rename` at the moment: https://elixir.bootlin.com/linux/latest/A/ident/vfs_rename

**Comment by tpetazzoni** [comment]
Both get_task_mm and vfs_rename symbols can now be searched without problem, so the issue seems to be fixed.
