### ISSUE TITLE
All symbol searches result in "Identifier Not Found"

### ISSUE THREAD

**Issue by MiguelElote** [bootlin/elixir#234]
I recently configured an offline Elixir server. Browsing through the projects for specific source code works properly. 
However, when I search for a specific symbol, the server always returns "Identified Not Used."

This URL for example returns several hundred hits.
https://elixir.bootlin.com/linux/v6.1-rc2/A/ident/read

The same URL on my local server returns "Identifier Not Used."
http://localhost/linux/v6.1-rc2/A/ident/read

I don't see errors in the logs, so I'm not sure where to start looking. Do you have any idea how to fix this?

**Comment by wanglouxiaozi** [comment]
make sure that you used the ctags with special version(universal-ctags_0+git20200526-0ubuntu1_amd64.deb), 
# ls -l $(which ctags)
 /usr/bin/ctags -> /etc/alternatives/ctags
# ls -l /etc/alternatives/ctags
 /etc/alternatives/ctags -> /usr/bin/ctags-universal

ctags-universal is the correct ctags version.

**Comment by jbrandeb** [comment]
And if you change ctags or your indexing fails or is stopped), how do you restart? do you have to reindex everything after doing a database delete? Is there an update equivalent to avoid reindexing?

**Comment by michaelopdenacker** [comment]
No, unfortunately, I don't know any solution other than reindexing from the start.
Sorry, that's horribly time consuming :-(

Closing the bug as you didn't have a sufficiently recent version of universal-ctags.
Thanks!
