### ISSUE TITLE
500 internal server error on Bootlin's instance

### ISSUE THREAD

**Issue by pcercuei** [bootlin/elixir#236]
- Open https://elixir.bootlin.com/linux/latest/source/include/linux/spi/spi.h#L1254
- Clicking on `spi_sync` or `spi_device`, everything works as intended.
- Clicking on `spi_transfer` or `spi_message` will result in a "500 internal server error" instead.

**Comment by cxw42** [comment]
I get the same results.

**Comment by pcercuei** [comment]
Seems to work now.
