### ISSUE TITLE
find-file-doc-comments.pl: Use of uninitialized value $source_lines[0] in pattern match (m//) 

### ISSUE THREAD

**Issue by michaelopdenacker** [bootlin/elixir#243]
Greetings,

I have this kind of issue when I run the ./utils/index-all-repositories (for example):
...
amazon-freertos - defs: 13000 (5.6%)
While processing /tmp/tmp.0LXajo4NYg: Use of uninitialized value $source_lines[0] in pattern match (m//) at /home/mike/work/git/github/elixir/find-file-doc-comments.pl line 134.

@cxw42 : maybe you have an idea why this happens...
Cheers
Michael.

**Comment by MaximeChretien** [comment]
Hi !
It looks like a duplicate of https://github.com/bootlin/elixir/issues/232.
You might find more informations there.

Have a nice day,
Maxime

**Comment by michaelopdenacker** [comment]
Good catch, thanks!
Closing this duplicate then.
Cheers
Michael.
