### ISSUE TITLE
built docker image, but can't access any source file

### ISSUE THREAD

**Issue by chujDK** [bootlin/elixir#252]
I built a (debian) docker indexing musl project, when it is done, i found it can only query idents.

i built it with `docker build -t elixir --build-arg GIT_REPO_URL=git://git.musl-libc.org/musl --build-arg PROJECT=musl .`. After that, i run `docker run <ID>`. If i access `http://172.17.0.2/musl/v1.2.4/A/ident/malloc`

![image](https://github.com/bootlin/elixir/assets/32593305/45734070-d54b-4b57-b176-9c382fa6120a)

it can return some result, but if I access `http://172.17.0.2/musl/v1.2.4/source` to see all source file, it shows nothing

![image](https://github.com/bootlin/elixir/assets/32593305/61b9874a-5dc2-4a7e-b99f-ace657caaf86)

this seems a permission problem, as the `/srv/elixir-data/$PROJECT/repo` is owned by root. If I run `chown -R www-data /srv/elixir-data/`, then access `http://172.17.0.2/musl/v1.2.4/source`

![image](https://github.com/bootlin/elixir/assets/32593305/70c5211c-4923-4ca1-9acf-c5d2b8e58a8f)

everything works fine now.

so my workaround is adding

```diff
diff --git a/docker/debian/Dockerfile b/docker/debian/Dockerfile
index d8cc7c1..c816c55 100644
--- a/docker/debian/Dockerfile
+++ b/docker/debian/Dockerfile
@@ -75,6 +75,8 @@ RUN \
   echo -e "\nHttpProtocolOptions Unsafe" >> /etc/apache2/apache.conf && \
   a2enmod cgi rewrite
 
+RUN chown -R www-data /srv/elixir-data
+
 EXPOSE 80
 
 ENTRYPOINT ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]
```

Maybe you can fix the problem in the dockerfile?

**Comment by zhijie-zhang** [comment]
kind of you ,

**Comment by fstachura** [comment]
Closing - a similar fix in in the current Dockerfile.

**Comment by fstachura** [comment]
Closing - a similar fix in in the current Dockerfile.
