### ISSUE TITLE
Add an option to hide the explorer

### ISSUE THREAD

**Issue by qodroi** [bootlin/elixir#255]
For those who don't have more than 1 monitor, the explorer on the left can be quite big and in my case it forces me to resize the browser to a specific, tiny size in order to have other applications open on the same monitor.

I see that when you resize the browser it closes automatically, it happens only when the browser size is really tiny though.

It’s not that big of a deal, but I believe it will help many users, including me. 

Thanks!

**Comment by tleb** [comment]
Done in #321 that is merged!
