### ISSUE TITLE
Remove the concept of `latest` tag?

### ISSUE THREAD

**Issue by tleb** [bootlin/elixir#261]
Currently, fetching the index page (`/`) of an Elixir instance redirects to `/$project/latest/source`. The `latest` in there represents a version tag with `latest` having a special meaning of the "the most recent non-RC version".

 - The redirect is handled by the webserver directly, as recommended in the README.
 - To interpret the `latest` tag: `http/web.py` uses `query.py`'s function `query`, that calls the `get_latest` function in `script.sh`. 

I'm not convinced by this default behavior. It means that by default, when accessing Elixir then navigating to something and copying the URL, the page returned is dependent on the current date (and the latest version released). That's not great for a tool that is used a lot to share code references with others, possibly in places were the link will be used for a long time.

Idea: HTTP redirect when the URL version component is `latest` to turn it into the actual latest version.

 - Now links don't break with new version releases.
 - This does not break the existing behavior: landing on the homepage takes us to `/linux/latest/source` that takes us to `/linux/v6.5.7/source` or whatever.
 - This requires no change to webservers.
 - This however adds a redirection when landing on the homepage. That can be fixed by having `http/web.py` redirect `/` requests directly to `/linux/v6.5.7/source` and removing the webserver rule.

It's an easy change, I wanted to gather opinions first. @michaelopdenacker maybe? :-)

**Comment by michaelopdenacker** [comment]
I agree with the change.
I have limited available time for the moment, but I'll be happy to take a patch!
Thanks
