### ISSUE TITLE
Offline search results differ from internet

### ISSUE THREAD

**Issue by rodtdan** [bootlin/elixir#262]
Hello,

So I've built an offline Elixir server for our users and was able to get the website up and running. The issue that I'm running into is that when searching here:

https://elixir.bootlin.com/linux/v5.13.12/A/ident/read

and comparing to my locally hosted on, the results drastically vary. My locally hosted one returns back with only 3 results. 

I'm trying to find out if there is a configuration that i need to edit/add in order to basically get the same results. 

I did find this: https://github.com/bootlin/elixir/issues/224

However, mine is built on a Fedora OS and it does not have ctag as a required package to install based on the manual installation guide. I even tried the same commands in the issue and do not get the same results. 

Any assistance would be greatly appreciated. I can provide logs/configuration settings if needed.

**Comment by tleb** [comment]
Doing a round of issues cleanup. `ctags` is a must-have for Elixir to work properly. The latest upstream version must be available globally (ie `ctags --version` should work).

Closing this issue. Feel free to discuss here if you are still facing issues!
