### ISSUE TITLE
supporting more file name extensions, plus cases

### ISSUE THREAD

**Issue by armijnhemel** [bootlin/elixir#27]
browsing through the code I saw the following:

    ext = filename[-2:]
    if not (ext == '.c' or ext == '.h'): continue

There are a few things that I think could be improved there. First of all, it ignores the cases of extensions: files that end with '.C' or '.H' are ignored. Second, it would be good to have more extensions, such as:

* .S (for assembler)
* .cxx, .c++, etc for C++ files

I would suggest to rsplit() the file name on the '.' character and check if the extension is in a supported list of extensions.

**Comment by michaelopdenacker** [comment]
Fixed now thanks to the above commit.
Many thanks for making this suggestion :)
Michael

**Comment by michaelopdenacker** [comment]
Just leave us 1 or 2 days to re-index all projects :)
