### ISSUE TITLE
Ability to get raw file

### ISSUE THREAD

**Issue by powellnorma** [bootlin/elixir#287]
Sometimes I'd like to take a diff of the same file on different versions. If there were a way to get the raw file, it would be easier to do this with elixir as source of the file. A parameter like `?raw` (or `?raw=1`) would already be enough in many cases - e.g. https://elixir.bootlin.com/linux/v6.7.10/source/fs/init.c?raw

**Comment by tleb** [comment]
Your suggestion does make sense. The `?raw` approach sounds right, being inspired (I guess) by pastebins. Questions that need answering:

 - Where to put the link to this raw resource? It could in the header bar or footer (the one that is fixed to the screen).
 - What should that link look like?

**Comment by powellnorma** [comment]
I'd probably use a "Download Icon" (even if a click on it does not download the file, but is just a link to the ?raw url) and put it the bottom bar.

In case the UI takes longer to get right, maybe we could add the functionality (via the URL) as a first step - and add UI later(?)

Thank you for considering this feature!

**Comment by tleb** [comment]
To move forward on this topic, here are some pointers to the related code:

 - Code that return HTML is the following. The whole http/web.py file will have to be adapted as it assumes it will emit HTML and it uses unconditionally the HTML template. https://github.com/bootlin/elixir/blob/fc472244250ebc48355b0c9cff7e4825b4782f5e/http/web.py#L266-L329
 - Footer HTML is found here: https://github.com/bootlin/elixir/blob/fc472244250ebc48355b0c9cff7e4825b4782f5e/templates/layout.html#L69-L73
 - CSS is found here: https://github.com/bootlin/elixir/blob/fc472244250ebc48355b0c9cff7e4825b4782f5e/http/style.css#L343-L405
