### ISSUE TITLE
Move from bsddb3 to berkeleydb

### ISSUE THREAD

**Issue by fstachura** [bootlin/elixir#290]
It seems that bsddb3 is now deprecated. Author suggests moving to berkeleydb.

https://pypi.org/project/bsddb3/

> This library is deprecated. If you are running Python 3 >= 3.6, please upgrade to [berkeleydb](https://pypi.org/project/berkeleydb/) library. Check [details](https://www.jcea.es/programacion/pybsddb.htm).

https://pypi.org/project/berkeleydb/

**Comment by tleb** [comment]
I am running on Python 3.12 and not noticing any issue. Indeed this needs to be done!

**Comment by tleb** [comment]
Done in #324 and commit 5e8eb779129df9e8bea2f4200e0afc34cf7af669
