### ISSUE TITLE
Symlinks redirect to invalid paths

### ISSUE THREAD

**Issue by fstachura** [bootlin/elixir#302]
See https://elixir.bootlin.com/u-boot/latest/source/tools/patman
Neither README.rst nor patman redirect to valid files.

**Comment by tleb** [comment]
So `tools/patman/README.rst` is a symlink to `tools/patman/patman.rst`. For some reason we mark it as `README.rst -> /tools/patman.rst`. The target path should instead be `/tools/patman/patman.rst`. [The URL of this file](https://elixir.bootlin.com/u-boot/v2024.07/source/tools/patman/patman.rst) works as expected.

Weird bug indeed.

**Comment by fstachura** [comment]
Symlinks can get tokenized.

See: https://elixir.bootlin.com/u-boot/v2023.10/source/arch/arm/dts
`imx6ull-colibri-emmc-eval-v3-u-boot.dtsi -> /arch/arm/imx6ull-colibri-eval-v3-u-boot.`
Notice dot at the end of the target.

https://github.com/bootlin/elixir/blob/master/http/web.py#L308
https://github.com/bootlin/elixir/blob/master/query.py#L166

On my instance, that symlink enters the `family != None` path. 

Opening a link directly does not redirect, but returns link contents (tokenized). 
https://elixir.bootlin.com/u-boot/v2023.10/source/arch/arm/dts/imx6ull-colibri-emmc-eval-v3-u-boot.dtsi
