### ISSUE TITLE
DT compatible search fails when comma is present, mangles the search string

### ISSUE THREAD

**Issue by lucaceresoli** [bootlin/elixir#309]
DT compatible search is currently broken when searching for a DT compatible string that contains a comma (which is frequent!), and perhaps other symbols that need escaping in HTML.

Steps to reproduce:
1. goto elixir.bootlin.com (currently redirects to https://elixir.bootlin.com/linux/v6.10.2/source)
2. in the drop-down list close to the "Search identifier" field, select the "DT compatible" search type
3. in the "Search identifier" field enter `fsl,imx6q-usdhc`
4. press enter or click on the magnifying lens

2 errors in the result page:
* `Identifier not used` is shown, even though it is present in the source
* the "Search identifier" field now contains `fsl%2Cimx6q-usdhc`

**Comment by fstachura** [comment]
I was just about to post about this :). Here is another example
https://elixir.bootlin.com/zephyr/v3.7.0/source/boards/luatos/esp32c3_luatos_core/esp32c3_luatos_core.dtsi#L13

What's interesting is that the popup seems to work. 
Replacing %2C with a comma in the search bar causes and "Identifier is invalid" - commas are indeed not allowed [here](https://github.com/bootlin/elixir/blob/master/http/web.py#L203). The search string is the same [in the old version](https://github.com/bootlin/elixir/blob/a627571baff358352cd0660185504f6e74e0e16d/http/web.py#L105). 

The identifier is probably unquoted to early.
