### ISSUE TITLE
off by one line number error

### ISSUE THREAD

**Issue by JuliaLawall** [bootlin/elixir#33]
Sometimes for a function I get sent to the line with the initial { rather than the function header.  At the moment, that occurs with of_iomap.  The entry in drivers/of/address.c links to line 761, but the function starts on line 760

http://elixir.free-electrons.com/linux/latest/source/drivers/of/address.c#L761

There are some other function links for of_iomap, but they go to the right place.

**Comment by michaelopdenacker** [comment]
Hi Julia
Thanks for the bug report!
As the source code has evolved a bit, here's a fixed link that reproduces this: https://elixir.bootlin.com/linux/v4.12.14/source/drivers/of/address.c#L761
I'll investigate this.

**Comment by JuliaLawall** [comment]
On Thu, 5 Apr 2018, Michael Opdenacker wrote:

>
> Hi Julia
> Thanks for the bug report!
> As the source code has evolved a bit, here's a fixed link that reproduces
> this:
> https://elixir.bootlin.com/linux/v4.12.14/source/drivers/of/address.c#L761
> I'll investigate this.

Thanks!

julia

**Comment by michaelopdenacker** [comment]
That's weird, this no longer happens with newer sources of the Linux kernel:
https://elixir.bootlin.com/linux/v5.2.1/ident/of_iomap
But it does (nothing changed) with the version you reported:
https://elixir.bootlin.com/linux/v4.12.14/ident/of_iomap
I'll try to find some time to investigate this at last...

**Comment by michaelopdenacker** [comment]
I'm getting closer.
There's an empty line at the beginning of the drivers/of/address.c file, which is not shown any more by the http/web.py script.
So the good news is that only http/web.py needs fixing, and the database is correct.

**Comment by pokazef** [comment]
Hi,
I tracked the issue down to Pygments: it has an option to remove leading and trailing blank lines that is on by default. Here comes a fix.
