### ISSUE TITLE
http://samplemedia.linaro.org/MPEG2/ http://samplemedia.linaro.org/MPEG4/SVT/

### ISSUE THREAD

**Issue by LaloQuera710** [bootlin/elixir#357]
TODO: add information on how you reached the error here and validate the details below.

---

Request date: 2024-12-17 23:28:20.530726
Path: /linux/v6.12.5/source/Documentation/x86/i386
Query string: 
Method: GET
Status code: 404 Not Found
Error title: File not found
Error details: This file does not exist.

**Comment by LaloQuera710** [comment]
[r.log](https://github.com/user-attachments/files/18172070/r.log)
[s.log](https://github.com/user-attachments/files/18172071/s.log)
[](url)

**Comment by fstachura** [comment]
Please open a new issue with more information about the bug you want to report.

**Comment by tleb** [comment]
Same as #359, I removed a `samplemedia.linaro.org/...` URL from title and some weird, probably unrelated, logs.
