### ISSUE TITLE
https://account.habr.com/ru/register/ZnU_yK4USQMyKh22OtfIh5zyfODVNeUwpnlVy5Db89-2jfZzoaX8qcQmHlNXY1zJwvdHmEobtsqXCUKsmdWq3NF2_Rw9Lpdm4iH5oZH8J-fEEkDJzL2hesDbY2R9RxQf2vmLBCkgrle5NehRKgyZ2jKWGpYRxyUPSW5_VmigXE9XFVetTh5xUrFvJ1ViEwiZNEwFTaDLPxAujrc5

### ISSUE THREAD

**Issue by LaloQuera710** [bootlin/elixir#359]
TODO: add information on how you reached the error here and validate the details below.

---

Request date: 2024-12-17 23:28:20.530726
Path: /linux/v6.12.5/source/Documentation/x86/i386
Query string: 
Method: GET
Status code: 404 Not Found
Error title: File not found
Error details: This file does not exist.

**Comment by LaloQuera710** [comment]
[r.log](https://github.com/user-attachments/files/18172199/r.log)
[s.log](https://github.com/user-attachments/files/18172200/s.log)

**Comment by LaloQuera710** [comment]
https://account.habr.com/ru/register/ZnU_yK4USQMyKh22OtfIh5zyfODVNeUwpnlVy5Db89-2jfZzoaX8qcQmHlNXY1zJwvdHmEobtsqXCUKsmdWq3NF2_Rw9Lpdm4iH5oZH8J-fEEkDJzL2hesDbY2R9RxQf2vmLBCkgrle5NehRKgyZ2jKWGpYRxyUPSW5_VmigXE9XFVetTh5xUrFvJ1ViEwiZNEwFTaDLPxAujrc5https://account.habr.com/ru/register/ZnU_yK4USQMyKh22OtfIh5zyfODVNeUwpnlVy5Db89-2jfZzoaX8qcQmHlNXY1zJwvdHmEobtsqXCUKsmdWq3NF2_Rw9Lpdm4iH5oZH8J-fEEkDJzL2hesDbY2R9RxQf2vmLBCkgrle5NehRKgyZ2jKWGpYRxyUPSW5_VmigXE9XFVetTh5xUrFvJ1ViEwiZNEwFTaDLPxAujrc5

**Comment by tleb** [comment]
The title and a comment contained a link to `account.habr.com/ru/register/...`, removed both. Also removed some odd looking logs that are unrelated to Elixir.
