### ISSUE TITLE
Wrong/missing indexing after double quote character

### ISSUE THREAD

**Issue by rupran** [bootlin/elixir#40]
In `kernel/trace/trace_events.c` in Linux, around 1300 lines are not properly indexed.

The problem starts here: https://elixir.bootlin.com/linux/v4.17/source/kernel/trace/trace_events.c#L2149
and seems to fix itself about 1300 lines later: https://elixir.bootlin.com/linux/v4.17/source/kernel/trace/trace_events.c#L3412

I strongly suspect the double quote (`if (*ptr == '"') {`) in the initial line to be the culprit, probably confusing the parser what's inside a string and what's not - this also causes some strings inside the faulty range to have links in them (e.g., 
https://elixir.bootlin.com/linux/v4.17/source/kernel/trace/trace_events.c#L3159)

**Comment by michaelopdenacker** [comment]
Closed now thanks to https://github.com/bootlin/elixir/pull/63
Many thanks for reporting this!
Michael
