### ISSUE TITLE
pre-generate all source file pages

### ISSUE THREAD

**Issue by yuanjianpeng** [bootlin/elixir#41]
I built a cross referencer site for kernel and glibc using elixir.
But I noticed that the load time of a page is very long about 500ms.
So can we support pre generate output of a source file to a static file, then we can load it without dynamic generate , that will speed up the visit time

**Comment by michaelopdenacker** [comment]
Hello,
Thanks for the suggestion!
For this need, we recommend to use an http cache in front of Apache running Elixir.
At Bootlin, we're happily using the Varnish Http Cache (https://varnish-cache.org/).
I updated the documentation to mention this.
Thanks again,
Cheers,
Michael.
