### ISSUE TITLE
Apostrophes in assembly are highlighted as string literals

### ISSUE THREAD

**Issue by lopsided98** [bootlin/elixir#45]
In assembly files, at least for ARM (I haven't checked other architectures), apostrophes in comments and code cause nearby text to be highlighted as if they were part of a string literal.

An example can be seen here: https://elixir.bootlin.com/linux/v4.19.5/source/arch/arm64/kernel/entry.S#L101

**Comment by michaelopdenacker** [comment]
Hi,
Thanks for this bug report. I confirm that it's still valid.
I'll investigate.
Cheers,
Michael.

**Comment by MaximeChretien** [comment]
Hi,
I think the bug was from pygments because the syntax highlighting is made by pygments. 
It looks like this bug has been fixed in the last version of pygments so we can close this issue.

Maxime

**Comment by lopsided98** [comment]
Yes, the example I originally linked looks fixed.
