### ISSUE TITLE
linenumbers and content do not fit

### ISSUE THREAD

**Issue by atar-axis** [bootlin/elixir#46]
Hi there!
Thanks for your hard work :)

Unfortunately it seems that on my system (latest linux, lastest chromium browser)
the line numbering does not fit the contents...

As you can see here, line 116 should be `struct bus_type {`

![image](https://user-images.githubusercontent.com/11148588/50807294-08300700-12fa-11e9-83ce-d3de6d0facb2.png)

When I can be of any help, please tell me!

**Comment by atar-axis** [comment]
Hum, when I change `pre { line-height: 1.2 }` to `pre { line-height: 1 }`, then it fits?!

**Comment by atar-axis** [comment]
what works is: 20px, 18px, 16px, 14px
what doesn't is: 19px, 17px, 15px

so every odd value is not working, every even does

**Comment by michaelopdenacker** [comment]
Hi,
Thank you for the bug report.
However, I cannot reproduce this issue, neither in Firefox nor in Chromium, whatever the zoom level I choose.
Don't hesitate to re-open if you still face it.
Thanks again,
Michael.
