### ISSUE TITLE
Elixir docker error

### ISSUE THREAD

**Issue by FiveTechSoft** [bootlin/elixir#47]
I have built Elixir docker using docker/Dockerfile

When running it, and trying to access localhost:8080 apache reports an internal server error

In apache error.log it is detailed:
AH02429: Response header name '<!--' contains invalid characters, aborting request

in the docker container at apache.conf there is:
-e
HttpProtocolOptions Unsafe

it seems as HttpProtocolOptions Unsafe it is not solving it. 

Apache version in the docker image is:
apachectl -v
Server version: Apache/2.4.25 (Debian)
Server built:   2018-11-03T18:46:19

**Comment by FiveTechSoft** [comment]
It seems as HttpProtocolOptions Unsafe is no working as expected with Apache/2.4.25 so I modified
Elixir Dockerfile to use Apache 2.4.10 this way:

FROM profideo/apache-2.4.10:latest
instead of:
FROM debian:latest

and removed apache2 from the apt-get install list in the Dockerfile.

**Comment by fstachura** [comment]
Closing - cannot reproduce with current Dockerfile.
