### ISSUE TITLE
[BUG] IndexError: list index out of range

### ISSUE THREAD

**Issue by rickyzhang82** [bootlin/elixir#49]
I tried the docker image on my code repo other than Linux kernel repository.

I enabled debug in web.py and output the error log to /tmp folder. 
```python
import cgitb
cgitb.enable(display=0, logdir='/tmp')
```

Here is the error I got from html page `/tmp/tmp32xjo7k5.html`:

```
...
<!-- The above is a description of an error in a Python program, formatted
     for a Web browser because the 'cgitb' module was enabled.  In case you
     are not reading this in a Web browser, here is the original traceback:

Traceback (most recent call last):
  File "/usr/local/elixir/http/web.py", line 138, in &lt;module&gt;
    lines = do_query ('versions')
  File "/usr/local/elixir/http/web.py", line 109, in do_query
    a = query.query (*args)
  File "/usr/local/elixir/http/../query.py", line 44, in query
    if db.vers.exists (p.split(b' ')[2]):
IndexError: list index out of range

-->

```

**Comment by dcsouthwick** [comment]
Hi there - I'd like to add a +1 to this- 
Tried on supplied Dockerfile and tried on a centos7 container. Same results. 
https://imgur.com/a/EfU7AXn

I suspect the supplied conf file rewrite ` RewriteRule "^/$" "/linux/latest/source" [R]` is to blame, as this directory does not exist (afaik). 
./query.py <cmd> <tag> <file> works fine... if it's not supposed to return anything.
Not sure where to go from here. Lack of documentation, will dig

**Comment by rickyzhang82** [comment]
In the end, I spent a day to build my own lxr container.  Well, elixir might be great but the configuration and documentation needs some improvement. 

If the container can't work out-of-the-box, no one would be interested in it to give a try out.

**Comment by dcsouthwick** [comment]
Yea - definitely agree here. I did some work to generalize the tag identification. It was hard-coded to split on spaces (' '), which breaks for basically everything that is not tagged like the "example" repos.
Currently looking at the db logic, I still get mismatches on table compare for tags. 

Will open a PR when I have time to finish up

**Comment by michaelopdenacker** [comment]
Greetings,

On 6/27/19 12:32 PM, David Southwick wrote:
>
> Yea - definitely agree here. I did some work to generalize the tag
> identification. It was hard-coded to split on spaces (' '), which
> breaks for basically everything that is not tagged like the "example"
> repos.
> Currently looking at the db logic, I still get mismatches on table
> compare for tags.
>

Thank for very much for your time and efforts. I'll be very happy to
merge the improvements that you will propose.

I'll do my best to spend more time or Elixir this summer.

Thanks again,

Michael.

-- 
Michael Opdenacker, CEO, Bootlin
Embedded Linux and Kernel engineering
https://bootlin.com

**Comment by dcsouthwick** [comment]
Thanks for your comments @michaelopdenacker. Please review #54 at your leisure

**Comment by michaelopdenacker** [comment]
Closing this issue as the code where it happened no longer exists.
Don't hesitate to create a new one if a similar one happens again.
