### ISSUE TITLE
Expose rest/json api for elixir

### ISSUE THREAD

**Issue by carmeli-tamir** [bootlin/elixir#51]
Hi,
Are there plans to expose an API for elixir? (e.g. get_symbol_definition, get_all_references)
If so I'd be willing to contribute.
Thanks!

**Comment by michaelopdenacker** [comment]
Hi,
Thank you for proposing your help!
Well, there is a command line interface you can use for retrieving a file or a symbol definition, for example. Look for "query.py" on https://github.com/bootlin/elixir/.
However, I'm clueless about rest/json APIs, so feel free to make proposals :)
Thanks,
Michael.

**Comment by michaelopdenacker** [comment]
Hi again,
So, are you still interested in making such a contribution?
Cheers,
Michael

**Comment by carmeli-tamir** [comment]
Hi,
Yes, I am still interested.
I want to first suggest how I'm planning to change the code so that you'd tell me what you think. First I need to inspect the code, and I'll suggest the change on my next message to the thread.

**Comment by michaelopdenacker** [comment]
Cool, waiting for your suggestions then :)
What kind of use to you plan to make with this REST API? Just curious about potential applications...
Thanks,
Michael

**Comment by carmeli-tamir** [comment]
The usage I was planning to do couple of months ago was to write a program to analyze the linux kernel symbols that my kernel module uses. For example, determine which of them are GPL only and in which kernel versions. This problem can be only partly solved in a different way - to compile the ko and check the symbol section for GPL only - but this only works for a given kernel version. Using the API I could do it for any kernel version and also to be notified on changes on new kernel versions for the symbols I use.

Regarding the change - I want to add a new file / folder which is parallel to the CGI interface - above the query command layer. This new file will implement a JSON api. At first - only for the 'ident' query.

I saw that for the 'ident' query, query.py returns a string which is then parsed by web.py using a regex. Do you mind if I changed it such that query.py returned a python object? This will make it easier for me to use the response in the JSON API, and also will save runtime since you wouldn't need to regex parse it. Is that OK with you?

**Comment by michaelopdenacker** [comment]
Hi,
Yes, I've never been very comfortable with such regexp parsing, making the code very difficult to read and maintain.
And nobody uses query.py without the CGI interface anyway.
So, yes, please propose your changes :) I'll be happy to review and test them.
Thanks,
Michael.

**Comment by pokazef** [comment]
Hi,
I, for one, use the command-line interface, so I would appreciate if #65 did not just toss it out the window.
It would be nice to use this opportunity to design a clean Python interface for queries and move the CLI code to its own front-end, next to the CGI and REST ones.

**Comment by michaelopdenacker** [comment]
Ooops, didn't know.
Are you using it for testing Elixir, or for another use case, like making all your Elixir queries from the command line, which could indeed be a convenient alternative to the browser?
Cheers,
Michael.

**Comment by pokazef** [comment]
I'm only using the CLI while debugging Elixir itself, but I feel it would be a step backward to get rid of it.
The real issue is that the CLI was the historical query interface: the old web.py actually ran the query as a new process. And although 990aaa6 turned it into a function call for performance reasons, the data format (i.e. plain text) stayed the same.
So I'm all for cleaning up this interface as @carmeli-tamir is proposing, but I would also like to keep the CLI as an "unpriviledged" front-end. I'll have time to work on this next week.

**Comment by michaelopdenacker** [comment]
Very cool, thanks :)

**Comment by michaelopdenacker** [comment]
Ok, I'll merge the pull request then, knowing that you'll take care of reviving the CLI.
Thanks a lot
