### ISSUE TITLE
Kernel config options

### ISSUE THREAD

**Issue by sgkimsm** [bootlin/elixir#57]
Usually searching some kernel config as identifier doesn't work, so "https://elixir.bootlin.com/linux/latest/ident/CONFIG_SCHEDSTATS" returns empty page.

But today I found it works with some kernel config like "https://elixir.bootlin.com/linux/latest/ident/CONFIG_PARAVIRT" and I think the reason is that it has something like "#undef CONFIG_PARAVIRT" in the code.

Then can we make it available generally for "#ifdef xxx"?
Use case: As mentioned, we can check the code very easily which is dependent to a certain kernel config in Linux kernel source tree.

**Comment by michaelopdenacker** [comment]
Effectively, proper processing of the kernel configuration options is definitely required.
This is not straightforward to implement as we should also parse the Kconfig files to find the corresponding definitions and to provide links to them.
I'll try to implement this, hopefully in the next months...

**Comment by michaelopdenacker** [comment]
Kernel configuration options are now indexed:
https://elixir.bootlin.com/linux/latest/K/ident/CONFIG_SCHEDSTATS

**Comment by sgkimsm** [comment]
Wow, cool!
Thanks for the update.
