### ISSUE TITLE
Thanks from DPDK

### ISSUE THREAD

**Issue by tmonjalo** [bootlin/elixir#59]
Elixir is successfully used by the DPDK project:
http://code.dpdk.org

Thank you Bootlin and contributors!

**Comment by michaelopdenacker** [comment]
Hi,
Thanks for the good news about this use of Elixir.
Would you mind sharing your projects/dpdk.sh file so that we can index this project on our website too?
2 instances is always better than just 1.
Thanks again,
Michael

**Comment by michaelopdenacker** [comment]
No longer needed. I took care of that.
Thanks again for the suggestion.
Michael
