### ISSUE TITLE
Some symbols not indexed

### ISSUE THREAD

**Issue by michaelopdenacker** [bootlin/elixir#64]
The 'nsmstate' symbol in fs/lockd/clntlock.c is not indexed, though it's not part of a blacklist.
See https://elixir.bootlin.com/linux/v5.4-rc1/source/fs/lockd/clntlock.c#L235

Similarly, in https://elixir.bootlin.com/linux/v5.4-rc1/source/arch/arm/kernel/hw_breakpoint.c,
"dscr" is indexed, but not "didr", even though they are declared in the same way.

**Comment by michaelopdenacker** [comment]
The above comment is not exactly true. "dscr" is defined elsewhere (see https://elixir.bootlin.com/linux/v5.4-rc1/ident/dscr), and hence is recognized as an identifier when we parse the code in https://elixir.bootlin.com/linux/v5.4-rc1/source/arch/arm/kernel/hw_breakpoint.c

**Comment by cxw42** [comment]
I'm not sure if this is the same issue, but I just noticed that `struct device` is a bit odd:

- At the [definition](https://elixir.bootlin.com/linux/v4.9.140/source/include/linux/device.h#L784), `device` is not linked or highlighted.
  - This despite the fact that other structs in that file are, e.g., `bus_type` [here](https://elixir.bootlin.com/linux/v4.9.140/source/include/linux/device.h#L109).
- The [search](https://elixir.bootlin.com/linux/v4.9.140/ident/device) does list `struct device` in the results.

Let me know if this is unrelated.  I did check other issues first but didn't find one that seemed to fit.  Thanks!

**Comment by michaelopdenacker** [comment]
Hi Chris,
Many thanks for this bug report.
Yes, this is unrelated to this bug. This happens because the "device" structure was wrongly blacklisted.
That's fixed now (see https://github.com/bootlin/elixir/commit/cb495269ebca404ebf8df8bd1f972e0bb35880f8), but it will take a few days to fix, as I'll need to regenerate the database completely.
Thanks again!
Michael

**Comment by cxw42** [comment]
Michael, much appreciated!

**Comment by michaelopdenacker** [comment]
Hi Chris,
Wow, reindexing the whole history takes time, because our database doesn't scale (we will address this through an internship in April: https://bootlin.com/internships/2020/en/internship-elixir.pdf)
That's done now. See https://elixir.bootlin.com/linux/latest/ident/device
Thanks again,
Michael.

**Comment by cxw42** [comment]
Michael, looks good!  Yes, I left the indexer running on my machine over a weekend and only got 1/3 of the way through!  I am glad to hear there are changes in the works.  I will try to get my PR for #78 in by the end of March.

**Comment by michaelopdenacker** [comment]
Hey Chris,
Thanks in advance, do your best. This will be highly appreciated by a vast number of users :)
Cheers,
Michael.

**Comment by michaelopdenacker** [comment]
Closing this bug
We don't want to support local variables.
