### ISSUE TITLE
Searching for implementations of message output functions

### ISSUE THREAD

**Issue by elfring** [bootlin/elixir#7]
I would like to look at implementations of [functions which output diagnostic information](https://www.kernel.org/doc/html/latest/process/coding-style.html#printing-kernel-messages "Printing kernel messages"). Now I observe that [a search by your evolving cross reference tool for a function like “dev_notice”](http://elixir.free-electrons.com/linux/v4.10/ident/dev_notice "Search result for dev_notice()") points [the header file “device.h”](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/linux/device.h?h=v4.10#n1230 "Device driver logging functionality") out. I would expect that another source file which contains corresponding implementations will be shown.

How are the chances that the software situation can be improved further similar to information in [the previous bug report “Identifier search doesn't find all function occurrences”](https://github.com/free-electrons/elixir/issues/5 "Improving the search results")?

**Comment by tpetazzoni** [comment]
For the specific case of ```dev_notice```, it is not possible I believe for a tool like Elixir to find the implementation. Indeed, the implementation is in ```drivers/base/core.c``` and looks like this:

```
#define define_dev_printk_level(func, kern_level)               \
void func(const struct device *dev, const char *fmt, ...)       \
{                                                               \
        struct va_format vaf;                                   \
        va_list args;                                           \
                                                                \
        va_start(args, fmt);                                    \
                                                                \
        vaf.fmt = fmt;                                          \
        vaf.va = &args;                                         \
                                                                \
        __dev_printk(kern_level, dev, &vaf);                    \
                                                                \
        va_end(args);                                           \
}                                                               \
EXPORT_SYMBOL(func);

define_dev_printk_level(dev_emerg, KERN_EMERG);
define_dev_printk_level(dev_alert, KERN_ALERT);
define_dev_printk_level(dev_crit, KERN_CRIT);
define_dev_printk_level(dev_err, KERN_ERR);
define_dev_printk_level(dev_warn, KERN_WARNING);
define_dev_printk_level(dev_notice, KERN_NOTICE);
define_dev_printk_level(_dev_info, KERN_INFO);
```

So, it's a macro that expands to the definition of all the dev_alert, dev_crit, dev_err, dev_warn, dev_notice functions. In order to find those out, Elixir would have to work on the pre-processed code, but that would lead to lots of other complexities.

So, I don't think this bug can be solved.

**Comment by elfring** [comment]
I noticed such challenges around [the generation of functions from macro calls](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/base/core.c?h=v4.10#n2807 "Construction of logging functions by define_dev_printk_level()") also a bit later. Thanks for your information.

* How do you think about to improve the display of search results for the shown identifiers?
* Would you like to distinguish any references between calls and usage for parameters?

**Comment by tpetazzoni** [comment]
We're not sure to understand what you want here, but we cannot parse macros, so basically it seems like we simply can't do want you want.

**Comment by elfring** [comment]
>We're not sure to understand what you want here, …

:crystal_ball: Can undesirable communication difficulties be adjusted anyhow for this issue?
