### ISSUE TITLE
Load times within China are unacceptable

### ISSUE THREAD

**Issue by twifty** [bootlin/elixir#79]
As you may be aware, the Great Firewall of China (GFW) blocks many external domains, especially anything 'google'.

Elixir makes use of a font hosted on [googleapis.com](https://github.com/bootlin/elixir/blob/db3b2c33c3cb1fcec8b14185a0a3c057444f77ba/http/style.css#L2) which is blocked by the GFW.

That particular domain times out, which in turn causes a page load to become slow. During this timeout period, no page content is displayed.

A few possible fixes:
1. Host the font on a CDN not blocked by the GFW. Preferably your own.
2. Late load the font by adding it to the page footer (allowing page content to be displayed with the wrong font).

**Comment by michaelopdenacker** [comment]
Hi,
Many thanks for reporting this issue.
Another problem with Google fonts is that Google can track your visits of our website. We don't want to participate in such tracking.
Would you have an alternative font to suggest in this particular case?
Thanks again,
Cheers,
Michael

**Comment by twifty** [comment]
It's been many years since I did any web development, so I'm a little out of touch with newer libraries.

Since elixir primarily renders code, how about looking into whichever font github uses?

**Comment by michaelopdenacker** [comment]
Hey, that's a good idea... I'll check.

**Comment by michaelopdenacker** [comment]
Fixed by https://github.com/bootlin/elixir/commit/17d1fb106dfa5539669df482dd9588820dcc4755
Thanks again,
Michael.

**Comment by twifty** [comment]
Nice quick fix. The website is so much better now.

**Comment by michaelopdenacker** [comment]
Great. Thank you for confirming this :)
