### ISSUE TITLE
Development server?

### ISSUE THREAD

**Issue by cxw42** [bootlin/elixir#87]
While working on #78, I wrote a small [Perl script](https://github.com/cxw42/elixir/blob/local-server/http/app.psgi) that provides a local development server wrapping the existing web.py.  Would the maintainers be interested in that script?  I have found it very helpful.

On the other hand, is there already a recommended development server?  I didn't see one listed in README.md, other than Apache itself.  I also didn't see one in the code, although I may have missed it.

**Comment by michaelopdenacker** [comment]
Hi Chris,
This sounds interesting indeed. So far, I'm making tests through a separate Apache install but I have to make my tests through a browser. I'd rather use the command line instead...
Is this way this script is about?
Your PRs are always welcome. I'll be happy to test :)
Thanks,
Michael.

**Comment by cxw42** [comment]
Good point about command line --- I hadn't thought of that.  This script as is prevents you from having to run the separate Apache.  However, it would make it easier to run command-line tests, and automated test suites.

**Comment by michaelopdenacker** [comment]
Hi Chris,
I understand better now. This sounds very useful.
Thanks a lot for all this :)
Michael

**Comment by cxw42** [comment]
While working through #133, I discovered [uwsgi](https://uwsgi-docs.readthedocs.io/en/latest/).  uwsgi can be used as a local development server for api.py.  If web.py were changed from CGI to WSGI, uwsgi could also be used for web.py.

As far as I can tell, changing to WSGI would improve speed in production, and make it easier to run development servers.  uwsgi can also [auto-reload on code changes](https://uwsgi-docs.readthedocs.io/en/latest/Snippets.html?highlight=reload#python-auto-reloading-development-only).  It looks like this would be a cleaner option than my development server.  What do you think?

**Comment by tpetazzoni** [comment]
@fstachura will improve the README to detail how to set up a local development server in an easy way using a Docker container

**Comment by fstachura** [comment]
#299 got merged recently, information about how to use the Docker image for development is now in README

**Comment by fstachura** [comment]
https://github.com/bootlin/elixir/pull/299 got merged recently, information about how to use the Docker image for development is now in README
