### ISSUE TITLE
Elixir + apache2 on ubuntu Error 400

### ISSUE THREAD

**Issue by shuidixu** [bootlin/elixir#90]
Hello

I followed your guide and I'm trying to setup elixir on apache2
this is my config:
```
  HttpProtocolOptions Unsafe
  # Required for HTTP
  <Directory /usr/local/elixir/http/>
      Options +ExecCGI
      AllowOverride None
      Require all granted
      SetEnv PYTHONIOENCODING utf-8
      SetEnv LXR_PROJ_DIR /home/ubuntu/sources/elixir_data/
  </Directory>

  # Required for the REST API
  <Directory /usr/local/elixir/api/>
      SetHandler wsgi-script
      Require all granted
      SetEnv PYTHONIOENCODING utf-8
      SetEnv LXR_PROJ_DIR /home/ubuntu/sources/elixir_data/
  </Directory>

  AddHandler cgi-script .py
  #Listen 80
  <VirtualHost *:80>
      ServerName hi
      DocumentRoot /usr/local/elixir/http

      # To enable REST api after installing mod_wsgi: Fill path and uncomment:
      #WSGIScriptAlias /api /usr/local/elixir/api/api.py

      RewriteEngine on
      RewriteRule "^/$" "/linux/latest/source" [R]
      RewriteRule "^/(?!api).*/(source|ident|search)" "/web.py" [PT]
  </VirtualHost>
  ~

```

and these are my directories:
```
 ls -la elixir_data/
total 16
drwxrwxrwx  4 ubuntu ubuntu 4096 Mar  5 12:30 .
drwxrwxr-x  9 ubuntu ubuntu 4096 Mar  5 12:11 ..
drwxrwxrwx  2 ubuntu ubuntu 4096 Mar  5 12:30 beyond10data
drwxrwxrwx 26 ubuntu ubuntu 4096 Mar  4 15:31 beyond2lte

```

these are the logs error.log of apache2 shows when i try to access elixir
```
[Thu Mar 05 12:59:29.957602 2020] [authz_core:debug] [pid 9464] mod_authz_core.c(809): [client xx.xx.xx.xx:12131] AH01626: authorization result of <RequireAny>: granted
[Thu Mar 05 12:59:47.716771 2020] [authz_core:debug] [pid 9466] mod_authz_core.c(809): [client xx.xx.xx.xx:12134] AH01626: authorization result of Require all granted: granted
[Thu Mar 05 12:59:47.716796 2020] [authz_core:debug] [pid 9466] mod_authz_core.c(809): [client xx.xx.xx.xx:12134] AH01626: authorization result of <RequireAny>: granted

```

I'm getting error 400 for some reason when I try to access elixir over http

I don't see anything bad there but I can't seem to understand why elixir doesn't work
 can anyone help me solve this?

**Comment by shuidixu** [comment]
Hi

I believe this issue resorts from two main problems:

1. I did not specify the right directory structure, but I've changed that, (repo and data are now under a specific project).
2. basedir is not parsed properly. I've modified web.py in order to verify this but I could'nt understand why this behavior happens.

For some reason only the first letter from the initial path is used, can anyone help understand why this happens? Even if I hardcore the paths it doesn't seem to work right.

**Comment by shuidixu** [comment]
anyone? :(

**Comment by carmeli-tamir** [comment]
Hi,
Let's make sure your directory structure is correct. The content of the directory "/home/ubuntu/sources/elixir_data/" should contain a project directory, for example "linux" or "barebox".
Then, under "linux" or "barebox" you must have 2 directories with the names "data" and "repo".
Refer to https://github.com/bootlin/elixir#configure-httpd

If you say that os.path.exists(data) and os.path.exists(repodir) do not seem to exist it's highly likely that there's a mistake in the folder hierarchy.

Please attach updated ls results if you are unable to resolve.

**Comment by fstachura** [comment]
Closing - many changes were made to the project since this issue was opened. Please open a new issue in case of similar problems.
