### ISSUE TITLE
Could script.sh use bash instead of sh?

### ISSUE THREAD

**Issue by cxw42** [bootlin/elixir#98]
Would it be a problem if script.sh used bash instead of vanilla sh?  It would be nice to be able to use `[[ ]]` conditionals and some of bash's other features.  What do you think?  Thanks!

**Comment by michaelopdenacker** [comment]
Hi Chris,

I guess the main reason to stick to /bin/sh (= /bin/dash) is being much smaller and faster to start. This matters as script.sh is heavily called on the server (for each client).

See https://unix.stackexchange.com/questions/148035/is-dash-or-some-other-shell-faster-than-bash

Closing this bug for now but don't hesitate to reopen it if you can convince me that the programming benefits outweight the performance costs.

Thanks,
Michael.

**Comment by cxw42** [comment]
Michael, thanks for the explanation!  That makes sense to me.
